'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),cp=require('child_process');
const root=process.cwd(),c=require(root+'/tools/local-audit/core.cjs'),runner=require(root+'/tools/local-audit-runner.cjs');
function remaining(state,queues){return Math.max(0,state.maxMinutes*60000-(state.overheadMs||0)-queues.reduce((n,q)=>n+q.elapsedMs,0));}
function nextPlan(repo,state,queues){
 assert.ok(queues.every(q=>q.batches.every(b=>['complete','exception'].includes(b.status))),'Unfinished queue cannot be skipped');
 const available=remaining(state,queues);if(!available)return null;
 const d=c.discover(repo),reserved=new Set(queues.flatMap(q=>q.batches.flatMap(b=>b.keys))),keys=d.pendingKeys.filter(k=>!reserved.has(k));if(!keys.length)return null;
 const q=c.plan(repo,{id:state.id+'-window-'+String(queues.length+1).padStart(3,'0'),maxBatches:state.maxBatchesPerQueue,maxMinutes:available/60000,maxAttempts:state.maxAttempts});q.batches=[];
 for(let n=0;n<keys.length&&q.batches.length<state.maxBatchesPerQueue;n+=10){const chosen=keys.slice(n,n+10);q.batches.push({id:'batch-'+String(q.batches.length+1).padStart(3,'0'),keys:chosen,status:'pending',attempts:[],reviews:[],validation:[],correctionPolicy:{maxCorrections:2,authorizationHash:state.authorizationHash},scenes:chosen.flatMap(key=>d.single[key].examples.map(s=>({exampleId:s.id,key,sourceHash:c.hash(s.beats),sourceRecordHash:c.hash(s),status:d.done.has(s.id)?'reference':'pending',reviewReference:d.done.get(s.id)?.reviewReference||null,attempts:0})))});}
 q.guard=c.fingerprint(repo);q.campaign={id:state.id,sharedMaxMinutes:state.maxMinutes,allocatedMinutes:q.limits.maxMinutes};c.validateBounds(q);return q;
}
function summary(state){const queues=state.queueFiles.map(c.read);return {campaign:state.id,status:state.status,stopReason:state.stopReason,elapsedMs:(state.overheadMs||0)+queues.reduce((n,q)=>n+q.elapsedMs,0),remainingMs:remaining(state,queues),maxMinutes:state.maxMinutes,overheadMs:state.overheadMs,queueFiles:state.queueFiles,queues:queues.map(c.summary),progress:c.discover(state.root).progress,nextPacket:state.nextPacket,pairPhase:'Pending; current integration adapter is single-card only. No pair reviews are inferred.'};}
async function resume(file,executable,exclusive){assert.ok(exclusive,'Use --exclusive-editor');const state=c.read(file);assert.equal(path.resolve(state.root),root);const unlock=runner.lock(path.dirname(file),state.id);let overheadStart=Date.now();const account=()=>{state.overheadMs+=Date.now()-overheadStart;overheadStart=Date.now();c.save(file,state);};try{
 state.status='running';state.stopReason=null;account();
 for(;;){let queues=state.queueFiles.map(c.read),q=queues.at(-1),qfile=state.queueFiles.at(-1);if(!remaining(state,queues)){state.stopReason='elapsed-time-limit';break;}
 if(q.batches.every(b=>['complete','exception'].includes(b.status))){for(const old of queues)for(const b of old.batches.filter(b=>b.status==='complete'))runner.verifyCompleted(old,b);assert.deepEqual(c.fingerprint(root),q.guard,'Campaign source drift');account();queues=state.queueFiles.map(c.read);const next=nextPlan(root,state,queues);if(!next){state.stopReason=remaining(state,queues)?'exact-pair-integration-adapter-required':'elapsed-time-limit';break;}q=next;qfile=path.join(path.dirname(file),q.id,'queue.json');assert.ok(!fs.existsSync(qfile));c.save(qfile,q);state.queueFiles.push(qfile);account();for(const b of q.batches){const out=path.join(path.dirname(qfile),'packets',b.id);cp.execFileSync(process.execPath,['tools/export-coach-batch.cjs','--kind','single','--keys',b.keys.join(','),'--out',out],{cwd:root,windowsHide:true,stdio:'pipe'});}account();console.log(JSON.stringify({planned:q.id,keys:q.batches.flatMap(b=>b.keys),sharedRemainingMs:remaining(state,state.queueFiles.map(c.read))}));}
 account();queues=state.queueFiles.map(c.read);const available=remaining(state,queues);if(!available){state.stopReason='elapsed-time-limit';break;}q=c.read(qfile);const cap=Math.min(q.limits.maxMinutes,(q.elapsedMs+available)/60000);if(cap<q.limits.maxMinutes){q.budgetHistory||=[];q.budgetHistory.push({at:new Date().toISOString(),from:q.limits.maxMinutes,to:cap,reason:'Reduce this window to the remaining shared campaign allowance; never reset elapsed time.'});q.limits.maxMinutes=cap;c.save(qfile,q);}const started=Date.now(),prior=q.elapsedMs;const result=await runner.run(qfile,executable,true);const used=c.read(qfile).elapsedMs-prior;state.overheadMs+=Math.max(0,Date.now()-overheadStart-used);overheadStart=Date.now();c.save(file,state);if(!['bounded-queue-complete','configured-batch-limit-reached'].includes(result.stopReason)){state.stopReason=result.stopReason;break;}
 }
 state.status='stopped';account();return summary(state);
 }catch(e){state.status='stopped';state.stopReason=e.message;state.lastError=e.stack;account();throw e;}finally{unlock();}}
async function main(){const [action,...args]=process.argv.slice(2),o={};for(let n=0;n<args.length;n++){assert.ok(args[n].startsWith('--'));const key=args[n].slice(2);assert.ok(['campaign','queue','authorization','codex','exclusive-editor'].includes(key));o[key]=args[n+1]&&!args[n+1].startsWith('--')?args[++n]:true;}const file=path.resolve(o.campaign||'.audit-runs/standing-campaign/campaign.json');assert.ok(file.startsWith(path.join(root,'.audit-runs')+path.sep));if(action==='init'){assert.ok(o['exclusive-editor']===true);assert.ok(!fs.existsSync(file));assert.ok(!fs.existsSync(path.join(root,'.audit-runner.lock')));const queue=path.resolve(o.queue),q=c.read(queue);assert.equal(path.resolve(q.root),root);c.save(file,{schema:1,id:'standing-coach',root,maxMinutes:q.limits.maxMinutes,maxBatchesPerQueue:q.limits.maxBatches,maxAttempts:q.limits.maxAttempts,authorizationHash:c.sha(fs.readFileSync(o.authorization)),queueFiles:[queue],overheadMs:0,status:'ready',stopReason:null,createdAt:new Date().toISOString()});console.log(JSON.stringify(summary(c.read(file)),null,2));}else if(action==='status')console.log(JSON.stringify(summary(c.read(file)),null,2));else if(action==='resume'){console.log(JSON.stringify(await resume(file,o.codex||'codex',o['exclusive-editor']===true),null,2));}else if(action==='recover-lock')runner.recoverLock(path.dirname(file));else throw Error('Use init|status|resume|recover-lock --campaign PATH [--queue PATH --authorization FILE] [--codex EXE --exclusive-editor]');}
module.exports={remaining,nextPlan,summary,resume,main};if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1;});
