'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),c=require('../tools/local-audit/core.cjs'),v=require('../tools/local-audit/coach2.cjs'),w=require('../tools/local-audit/worker.cjs'),f=require('./fixtures/local-audit.cjs');
const evidence='STRUCTURAL FIXTURE ONLY: B2 informs A3; B4 offers a bicycle and A5 uses it.';
test('production transition refuses legacy integration under coach2 without resetting old state',()=>{v.assertLegacyExecution({});assert.throws(()=>v.assertLegacyExecution({requiredRubricVersion:'coach-2.0'}),/legacy resume/);});
function diagnostic(beats){return {rubricVersion:v.version,dialogueHash:c.hash(beats),inspectionMode:'internal-dialogue-first',situation:evidence,stated:evidence,inferred:evidence,missing:evidence,firstDefect:evidence,sceneOutline:evidence,mechanism:evidence,mandatoryGates:Object.fromEntries(v.gateIds.map(g=>[g,{decision:'PASS',evidence}])),transitions:Object.fromEntries(v.links.map(g=>[g,{decision:'PASS',evidence}])),humanReviewed:false,liveTested:false};}
function fixture(){const input=structuredClone(f.input());input.rubric.version=v.version;const writer=f.writer(input);writer.records.forEach(r=>r.coach2=diagnostic(input.records.find(x=>x.exampleId===r.exampleId).before.beats));const ri=c.reviewerInput(input,writer),review=f.review(ri);review.records.forEach(r=>r.coach2=diagnostic(ri.records.find(x=>x.exampleId===r.exampleId).beats));return {input,writer,ri,review};}
test('coach2 production schema/prompt and validators require versioned evidence; historical fixtures remain valid',()=>{const {input,writer,ri,review}=fixture();c.validateWriter(input,writer);c.validateReview(ri,review);assert.equal(ri.rubric.version,v.version);assert.ok(v.extendSchema(w.schemas.writer).properties.records.items.required.includes('coach2'));assert.match(w.prompt('reviewer',ri,'fixture','',null),/G1: legible/);assert.match(w.prompt('writer',input,'fixture','',null),/Historical coach-1.0 acceptance is not coach-2.0/);const old=f.input();c.validateWriter(old,f.writer(old));c.validateReview(c.reviewerInput(old,f.writer(old)),f.review(c.reviewerInput(old,f.writer(old))));delete review.records[0].coach2;assert.throws(()=>c.validateReview(ri,review),/evidence required/);});
for(const gate of v.gateIds)for(const decision of ['FAIL','UNCLEAR'])test('100-point fixture cannot override '+gate+' '+decision,()=>{const {ri,review}=fixture();review.records[0].coach2.mandatoryGates[gate].decision=decision;assert.throws(()=>c.validateReview(ri,review),/mandatory gates/);review.records[0].accept=false;c.validateReview(ri,review);});
test('every transition is mandatory, not a repeated-word shortcut',()=>{for(const link of v.links){const {ri,review}=fixture();review.records[0].coach2.transitions[link].decision='UNCLEAR';assert.throws(()=>c.validateReview(ri,review),/G3 cannot pass/);}});
test('weak originals cannot be retained and exact hashes/no human claims are enforced',()=>{const {input,writer,ri,review}=fixture();writer.records[0].coach2.mandatoryGates.G1.decision='FAIL';assert.throws(()=>c.validateWriter(input,writer),/weak original/);review.records[0].coach2.dialogueHash='0'.repeat(64);assert.throws(()=>c.validateReview(ri,review),/hash mismatch/);review.records[0].coach2=diagnostic(ri.records[0].beats);review.records[0].coach2.humanReviewed=true;assert.throws(()=>c.validateReview(ri,review));});
test('unchanged numerical thresholds and arithmetic correction',()=>{const {ri,review}=fixture();const r=review.records[0];for(const x of Object.values(r.secondPass.ratings))x.score=4;r.secondPass.weightedTotal=80;assert.throws(()=>c.validateReview(ri,review),/Acceptance must follow/);r.secondPass.weightedTotal=99;const fixed=w.deriveTotals(review,'reviewer');assert.equal(fixed.output.records[0].secondPass.weightedTotal,80);assert.equal(r.secondPass.weightedTotal,99);});
test('targeted correction preserves coach2 original assessment as well as scores',()=>{const {writer,review}=fixture(),runner=require('../tools/local-audit-runner.cjs');review.records[0].accept=false;const req=runner.correctionRequest(writer,review),changed=structuredClone(writer);changed.records[0].coach2.firstDefect='Changed historical diagnosis';assert.throws(()=>runner.validateCorrection(changed,req),/original coach-2.0/);});
