"use strict";
const assert=require('node:assert/strict');const b=require('../hint-bible.js');
assert.deepEqual(b.policies.map(p=>p.id),['full','nudges','after-attempt','off']);
assert.equal(b.normalizePolicy('old-or-invalid'),'full');
assert.equal(b.getPolicy('full').allowsDepth,true);
assert.equal(b.getPolicy('nudges').allowsDepth,false);
assert.equal(b.getPolicy('after-attempt').requiresUnlock,true);
assert.equal(b.getPolicy('off').allowsSingle,false);
assert.equal(b.getPolicy('off').allowsCombination,false);
assert.equal(b.getSubthemeGuidance,undefined);
console.log('✓ Example availability policies preserve saved IDs without coaching templates');
