'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const root=process.cwd(),c=require(root+'/tools/local-audit/core.cjs'),driver=require(process.env.CAMPAIGN_DRIVER||root+'/tools/local-audit-campaign.cjs'),f=require(root+'/tests/fixtures/local-audit.cjs');
function fixture(){const repo=fs.mkdtempSync(path.join(os.tmpdir(),'imprompt-campaign-fixture-')),records={};for(let n=1;n<=80;n++){const key='S'+String(n).padStart(2,'0');records[key]={title:'Fixture '+key,instruction:'Use the explicit fixture behavior.',contentVersion:'1',examples:f.input().records.map((r,i)=>({...r.before,id:key+'-single-'+(i?'b':'a')}))};}c.save(path.join(repo,'examples/authoring/single-scenes.json'),{records});c.save(path.join(repo,'examples/authoring/pair-scenes.json'),{});c.save(path.join(repo,'examples/manifest.json'),{counts:{pairExamples:115200}});c.save(path.join(repo,'package.json'),{version:'fixture'});fs.mkdirSync(path.join(repo,'editorial'));return repo;}
test('campaign time is cumulative across queues and overhead; a new queue never renews it',()=>{const s={maxMinutes:240,overheadMs:60000};assert.equal(driver.remaining(s,[{elapsedMs:200*60000},{elapsedMs:30*60000}]),9*60000);assert.equal(driver.remaining(s,[{elapsedMs:240*60000}]),0);});
test('next window skips completed and exception keys, keeps exact hashes, and stays capped at five batches',()=>{const repo=fixture(),state={id:'fixture',maxMinutes:240,maxBatchesPerQueue:5,maxAttempts:2,authorizationHash:'fixture',overheadMs:60000},old={elapsedMs:200*60000,batches:[{status:'complete',keys:Array.from({length:10},(_,n)=>'S'+String(n+1).padStart(2,'0'))},{status:'exception',keys:Array.from({length:10},(_,n)=>'S'+String(n+11).padStart(2,'0'))}]},q=driver.nextPlan(repo,state,[old]);assert.equal(q.limits.maxMinutes,39);assert.equal(q.batches.length,5);assert.equal(q.batches[0].keys[0],'S21');assert.equal(q.batches.at(-1).keys.at(-1),'S70');assert.equal(q.batches[0].correctionPolicy.maxCorrections,2);const source=c.discover(repo);for(const b of q.batches)for(const s of b.scenes)assert.equal(s.sourceRecordHash,c.hash(source.single[s.key].examples.find(e=>e.id===s.exampleId)));c.validateBounds(q);});
test('unfinished queues cannot be skipped and exhausted time creates no next window',()=>{const repo=fixture(),s={id:'fixture',maxMinutes:240,maxBatchesPerQueue:5,maxAttempts:2,authorizationHash:'fixture',overheadMs:0};assert.throws(()=>driver.nextPlan(repo,s,[{elapsedMs:1,batches:[{status:'active',keys:['S01']}]}]),/Unfinished queue/);assert.equal(driver.nextPlan(repo,s,[{elapsedMs:240*60000,batches:[{status:'exception',keys:['S01']}]}]),null);});

const allowance=require(root+'/tools/local-audit/execution-allowance.cjs');
test('explicit recovery allowance preserves exhausted history and never renews on resume',()=>{const q=[{elapsedMs:14400000}],s={status:'stopped',maxMinutes:240,overheadMs:100,queueFiles:['unchanged']},before=structuredClone(s),now=1000000;const w=allowance.authorize(s,q,{minutes:240,authorizationHash:'a'.repeat(64),snapshot:'fixture',now});assert.equal(w.priorElapsedMs,14400100);assert.equal(s.maxMinutes,before.maxMinutes);assert.equal(s.overheadMs,before.overheadMs);assert.deepEqual(s.queueFiles,before.queueFiles);assert.equal(allowance.remaining(s,q,now),14400000);assert.equal(allowance.remaining(s,q,now+14400001),0);assert.equal(s.recoveryGate.status,'pending');assert.throws(()=>allowance.authorize(s,q,{minutes:240,authorizationHash:'a'.repeat(64),snapshot:'fixture',now:now+14400001}),/already consumed/);});
test('allowance bounds and historical time rollback are rejected',()=>{const q=[{elapsedMs:14400000}],base={status:'stopped',maxMinutes:240,overheadMs:0};assert.throws(()=>allowance.authorize(structuredClone(base),q,{minutes:241,authorizationHash:'b'.repeat(64),snapshot:'fixture',now:1}),/capped/);const s=structuredClone(base);allowance.authorize(s,q,{minutes:1,authorizationHash:'b'.repeat(64),snapshot:'fixture',now:1});assert.throws(()=>allowance.remaining(s,[{elapsedMs:1}],2),/backwards/);assert.equal(allowance.remaining(s,[{elapsedMs:14460000}],2),0);});

const bindingRecovery=require(root+'/tools/local-audit/binding-recovery.cjs');
test('a later explicit time grant preserves the already verified delivery gate without redoing completed work',()=>{const gate={status:'verified',nativeVerification:'FIXTURE prior actual proof reference',completion:'FIXTURE unchanged completed batch'},s={status:'stopped',maxMinutes:240,overheadMs:0,recoveryGate:gate},q=[{elapsedMs:14400000}];allowance.authorize(s,q,{minutes:30,authorizationHash:'c'.repeat(64),snapshot:'FIXTURE prior history',now:100});assert.strictEqual(s.recoveryGate,gate);assert.equal(q[0].elapsedMs,14400000);assert.equal(s.executionAllowances.length,1);assert.equal(allowance.remaining(s,q,100),1800000);});
function provenanceFixture(){const pairs=['a','b'].map(v=>({id:'S53+D60-'+v,beats:[{speaker:'A',text:'FIXTURE: unchanged dialogue.'}],seedUse:'FIXTURE: inaccurate timing claim.',exampleVersion:'fixture',editorialStatus:'pending'}));return {pairs,changes:pairs.map(p=>({exampleId:p.id,beforeSeedUse:p.seedUse,afterSeedUse:'FIXTURE: A1 already retains authority before B responds.',beforeRecordHash:c.hash(p),afterRecordHash:c.hash({...p,seedUse:'FIXTURE: A1 already retains authority before B responds.'}),reason:'FIXTURE ONLY: A1 establishes authority before B2.'}))};}
test('provenance repair changes only the two declared metadata strings',()=>{const {pairs,changes}=provenanceFixture(),after=bindingRecovery.changedPairs(pairs,changes);assert.deepEqual(after.map(p=>p.beats),pairs.map(p=>p.beats));assert.deepEqual(after.map(p=>[p.id,p.exampleVersion,p.editorialStatus]),pairs.map(p=>[p.id,p.exampleVersion,p.editorialStatus]));assert.throws(()=>bindingRecovery.changedPairs(pairs,[{...changes[0],exampleId:'S06+D49-b'},changes[1]]));assert.throws(()=>bindingRecovery.changedPairs(pairs,[{...changes[0],beats:[]},changes[1]]));assert.throws(()=>bindingRecovery.changedPairs(pairs,[{...changes[0],beforeRecordHash:'wrong'},changes[1]]));});
test('binding recovery cannot clear an unresolved dialogue or another binding',()=>{const input=f.input(),writer=f.writer(input),review=f.review(c.reviewerInput(input,writer));review.records[0].accept=false;assert.throws(()=>bindingRecovery.derive(input,writer,review,{},{}),/unresolved dialogue/);review.records[0].accept=true;writer.bindings[0].compatible=false;assert.throws(()=>bindingRecovery.derive(input,writer,review,{},{}),/explicitly declared binding issue/);});

test('replays the exact S41-b and S44-a short-label failures without changing dialogue',()=>{for(const [key,index,label] of [['S41',1,'Ordinary diligence.'],['S44',0,'General pessimism.']]){const input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01',key)),writer=f.writer(input);writer.bindings[0].key=key;const before=c.hash(writer.records.map(r=>r.beats));writer.records[index].confusableConcept=label;assert.throws(()=>c.validateWriter(input,writer),new RegExp(key+'-single-'+(index?'b':'a')+' confusableConcept'));assert.equal(c.hash(writer.records.map(r=>r.beats)),before);}});

test('reopened earlier work precedes the later interrupted queue and reserves checkpoint time',()=>{assert.equal(driver.nextQueueIndex([{batches:[{status:'pending'}]},{batches:[{status:'active'}]}]),0);assert.equal(driver.nextQueueIndex([{batches:[{status:'exception'}]},{batches:[{status:'active'}]}]),1);assert.equal(driver.workRemaining({maxMinutes:240,overheadMs:0,checkpointReserveMinutes:75},[{elapsedMs:100*60000}]),65*60000);});
test('an explicit technical recovery does not add editorial correction rounds',()=>{const policy=require(root+'/tools/local-audit/editorial-policy.cjs'),q={limits:{maxAttempts:2}},prefix=[{id:'attempt-01',status:'failed'},{id:'attempt-02',status:'failed'}],b={correctionPolicy:{maxCorrections:2,authorizationHash:'fixture'},attempts:[...prefix],technicalRecovery:{maxAttempts:1,startIndex:2,authorizationHash:'a'.repeat(64),snapshot:'fixture',reason:'FIXTURE explicit technical recovery.',originalAttemptsHash:c.hash(prefix)}};assert.equal(policy.technicalLimit(q,b),3);assert.equal(policy.mayStart(q,b),true);b.attempts.push(...[3,4,5].map(n=>({id:'attempt-0'+n,status:'rejected',critique:{review:{records:[{accept:false}]}}})));assert.equal(policy.mayStart(q,b),false);});
test('metadata-only correction rejects dialogue or first-pass changes',()=>{const validate=require(root+'/tools/local-audit-recover-saved.cjs').validateMetadataCorrection,old={records:[{exampleId:'S41-single-b',confusableConcept:'Ordinary diligence.',beats:[{speaker:'A',text:'FIXTURE untouched.'}],firstPass:{weightedTotal:10}}]},next=structuredClone(old);next.records[0].confusableConcept='FIXTURE ordinary diligence versus belonging anxiety.';validate(old,next);next.records[0].beats[0].text='Changed';assert.throws(()=>validate(old,next),/changed saved dialogue/);});

test('S43 recovery changes only the demonstrated a provenance mismatch and refuses other scope',()=>{const br=require(root+'/tools/local-audit/binding-recovery.cjs'),pairs=[{id:'S43+D32-a',seedUse:'FIXTURE inaccurate shortcut permission.',beats:[{speaker:'A',text:'FIXTURE protected order.'}]},{id:'S43+D32-b',seedUse:'FIXTURE accurate contained trial.',beats:[]}],after={...pairs[0],seedUse:'FIXTURE A1 delegates testing while protecting the order.'},changes=[{exampleId:pairs[0].id,beforeSeedUse:pairs[0].seedUse,afterSeedUse:after.seedUse,beforeRecordHash:c.hash(pairs[0]),afterRecordHash:c.hash(after),reason:'FIXTURE exact A1 provenance timing and permission correction.'}];assert.equal(br.scopeKey({bindingKey:'S43',changes}),'S43');const result=br.changedPairs(pairs,changes);assert.deepEqual(result[1],pairs[1]);assert.deepEqual(result[0].beats,pairs[0].beats);assert.throws(()=>br.scopeKey({bindingKey:'S06',changes}),/demonstrated/);assert.throws(()=>br.changedPairs(pairs,[{...changes[0],exampleId:'S43+D32-b'}]),/documented/);});

test('interrupted phase recovery preserves failures and allows only the uncompleted correction',()=>{
 const policy=require('../tools/local-audit/editorial-policy.cjs'),b={correctionPolicy:{maxCorrections:2,authorizationHash:'existing'},attempts:[{status:'failed',error:'old failure'},{status:'rejected',critique:{review:{records:[{accept:false}]}}},{status:'rejected',critique:{review:{records:[{accept:false}]}}},{status:'failed',error:'writer timedOut=true'}]},q={limits:{maxAttempts:2}};
 b.technicalRecovery={kind:'interrupted-phase',maxAttempts:1,startIndex:4,authorizationHash:'a'.repeat(64),snapshot:'immutable-original.json',reason:'Resume interrupted second correction only.',originalAttemptsHash:c.hash(b.attempts)};assert.equal(policy.mayStart(q,b),true);b.attempts.push({status:'rejected',critique:{review:{records:[{accept:false}]}}});assert.equal(policy.mayStart(q,b),false);b.attempts[0].error='rewritten';assert.throws(()=>policy.validate(q,b),/history changed/);
});

test('accepted but unapplied groups remain resumable ahead of later queues',()=>{const campaign=require('../tools/local-audit-campaign.cjs');const b={status:'partial',partialTerminal:true,perExampleFindings:{eligible:['S01-single-a']},scenes:[{exampleId:'S01-single-a',status:'accepted-staged'}]},later={batches:[{status:'pending',scenes:[]}]};assert.equal(campaign.nextQueueIndex([{batches:[b]},later]),0);b.scenes[0].acceptedHash='verified';assert.equal(campaign.nextQueueIndex([{batches:[b]},later]),1);b.pendingIntegration={journal:'pending'};assert.equal(campaign.nextQueueIndex([{batches:[b]},later]),0);});
test('release filtering excludes redundant snapshots and binaries while preserving validation logs',()=>{const include=require('../tools/local-audit/checkpoint.cjs').includeReport;for(const p of ['reports/campaign-snapshot/queue.json','reports/old.zip','reports/extracted/app.js','reports/node_modules/dependency.js'])assert.equal(include(p),false,p);for(const p of ['reports/release-verification/source-validation/test.stdout.log','reports/old.zip.verification.json','reports/final-results.json'])assert.equal(include(p),true,p);});

test('interrupted correction remains pending only until its next attempt is recorded',()=>{const pe=require('../tools/local-audit/per-example.cjs'),b={attempts:[{},{}],technicalRecovery:{kind:'interrupted-phase',startIndex:2}};assert.equal(pe.pendingCorrection(b),true);b.attempts.push({});assert.equal(pe.pendingCorrection(b),false);});

// Include the source-only pause regression in the established full suite.
require('./source-checkpoint.test.cjs');
