'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const c=require('../tools/local-audit/core.cjs'),f=require('./fixtures/local-audit.cjs');
test('explicit fixture accepts exact original and a separate rubric-matched reread',()=>{const i=f.input(),w=c.validateWriter(i,f.writer(i)),ri=c.reviewerInput(i,w),r=c.validateReview(ri,f.review(ri));assert.ok(c.allAccepted(w,r));});
test('reviewer input contains exact cards and dialogue, without writer assessments',()=>{const i=f.input(),w=f.writer(i);w.records[0].reason='SECRET_WRITER_IMPROVEMENT';const ri=c.reviewerInput(i,w),serialized=JSON.stringify(ri);assert.ok(!/"firstPass"|"weightedTotal"|SECRET_WRITER_IMPROVEMENT|"reservation"|"decision"|"beforeHash"/.test(serialized));assert.deepEqual(ri.records[0].card,i.records[0].card);assert.deepEqual(ri.records[0].beats,w.records[0].beats);});
test('optimistic acceptance, empty gates, stale hashes, duplicate and missing scenes fail closed',()=>{const i=f.input(),w=f.writer(i),ri=c.reviewerInput(i,w);for(const mutate of [r=>r.records.pop(),r=>r.records.push(r.records[0]),r=>r.records[0].candidateHash='stale',r=>r.records[0].hardGates={},r=>{r.records[0].hardGates.b4CausesA5=false;}]){const r=f.review(ri);mutate(r);assert.throws(()=>c.validateReview(ri,r));}});
test('weak model review remains pending despite valid artifact and process success',()=>{const i=f.input(),w=f.writer(i),ri=c.reviewerInput(i,w),r=f.review(ri);r.records[0].secondPass.ratings.cardFidelity.score=2;r.records[0].secondPass.weightedTotal=82;r.records[0].accept=false;c.validateReview(ri,r);assert.equal(c.allAccepted(w,r),false);});
test('retaining a weak original, stage directions and invented scene IDs are rejected',()=>{const i=f.input();for(const mutate of [w=>{w.records[0].firstPass.ratings.cardFidelity.score=2;w.records[0].firstPass.weightedTotal=82;},w=>w.records[0].beats[0].action='a movement',w=>w.records[0].exampleId='invented']){const w=structuredClone(f.writer(i));mutate(w);assert.throws(()=>c.validateWriter(i,w));}});
test('previously completed alternative is reference-only and never assigned to workers',()=>{const i=f.input();i.records[0].reference=true;const w=f.writer(i);c.validateWriter(i,w);const ri=c.reviewerInput(i,w),r=f.review(ri);c.validateReview(ri,r);assert.equal(r.records.length,1);assert.deepEqual(ri.records[0].beats,i.records[0].before.beats);});

const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),integration=require('../tools/local-audit/integration.cjs'),worker=require('../tools/local-audit/worker.cjs');
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'imprompt-runner-fixture-'));
test('interrupted integration resumes exact writes and refuses concurrent unrelated changes',()=>{const root=temp(),stage=temp(),dir=temp();c.save(path.join(root,'examples/authoring/single-scenes.json'),{old:true});c.save(path.join(root,'preserved.json'),{userEdit:true});c.save(path.join(stage,'examples/authoring/single-scenes.json'),{new:true});c.save(path.join(stage,'preserved.json'),{userEdit:true});const guard=c.fingerprint(root),journal=path.join(dir,'journal.json');integration.makeTransaction(root,stage,journal,'editorial/local-fixture',guard);assert.throws(()=>integration.applyTransaction(journal,1),/Fixture interruption/);assert.equal(c.read(journal).status,'prepared');integration.applyTransaction(journal);assert.deepEqual(c.fingerprint(root),c.fingerprint(stage));c.save(path.join(root,'preserved.json'),{anotherEditor:true});assert.throws(()=>integration.applyTransaction(journal),/Concurrent source conflict/);assert.equal(c.read(path.join(root,'preserved.json')).anotherEditor,true);});
test('transaction refuses changes to playable cards and preserves pre-existing work',()=>{const root=temp(),stage=temp(),dir=temp();c.save(path.join(root,'cards.json'),{wording:'original'});c.save(path.join(stage,'cards.json'),{wording:'unauthorized'});assert.throws(()=>integration.makeTransaction(root,stage,path.join(dir,'journal.json'),'editorial/local-fixture',c.fingerprint(root)),/Unexpected staging mutation/);assert.equal(c.read(path.join(root,'cards.json')).wording,'original');});
test('one live integration lock prevents a second runner or unsafe recovery',()=>{const {lock,recoverLock}=require('../tools/local-audit-runner.cjs'),root=temp(),release=lock(root,'fixture');assert.throws(()=>lock(root,'another'),/EEXIST/);assert.throws(()=>recoverLock(root),/still running/);release();assert.ok(!fs.existsSync(path.join(root,'.audit-runner.lock')));});
test('worker success without an output artifact is insufficient',async()=>{await assert.rejects(worker.invoke({executable:'fixture-only',role:'writer',input:f.input(),dir:temp(),rubricText:'fixture',timeoutMs:1000,runCommand:async()=>({code:0,timedOut:false})}),/without artifact/);});
test('saved worker proof resumes without another invocation; tampering stops reuse',async()=>{const dir=temp(),input=f.input();let calls=0;const runCommand=async(exe,args,cwd,log)=>{calls++;assert.ok(args.includes('read-only')&&args.includes('--ephemeral'));assert.ok(!args.some(a=>/dangerously|ignore-rules|add-dir/.test(a)));c.save(args[args.indexOf('--output-last-message')+1],f.writer(input));fs.writeFileSync(log+'.stdout.log',JSON.stringify({type:'turn.completed',usage:{input_tokens:12,output_tokens:7}})+'\n');return {code:0,timedOut:false,elapsedMs:3,log};};const opts={executable:'fixture-only',role:'writer',input,dir,rubricText:'fixture',timeoutMs:1000,runCommand};await worker.invoke(opts);await worker.invoke(opts);assert.equal(calls,1);c.save(path.join(dir,'writer.json'),{});await assert.rejects(worker.invoke(opts),/artifact changed/);});
test('unproven interrupted output and tool-using reviewer are never accepted',async()=>{const dir=temp();c.save(path.join(dir,'reviewer.json'),{});await assert.rejects(worker.invoke({executable:'fixture-only',role:'reviewer',input:{},dir,rubricText:'fixture',timeoutMs:100}),/Unproven partial/);const next=temp();await assert.rejects(worker.invoke({executable:'fixture-only',role:'reviewer',input:{records:[]},dir:next,rubricText:'fixture',timeoutMs:100,runCommand:async(exe,args,cwd,log)=>{c.save(args[args.indexOf('--output-last-message')+1],{});fs.writeFileSync(log+'.stdout.log',[{type:'item.completed',item:{type:'command_execution'}},{type:'turn.completed'}].map(JSON.stringify).join('\n'));return {code:0,timedOut:false};}}),/used tools/);});
test('queue bounds, explicit IDs and completed hashes come from fixtures, not release assumptions',()=>{const root=temp(),i=f.input(),source={records:{S01:{examples:i.records.map(r=>r.before)},S02:{examples:i.records.map(r=>({...r.before,id:r.before.id.replace('S01','S02')}))}}};c.save(path.join(root,'examples/authoring/single-scenes.json'),source);c.save(path.join(root,'examples/authoring/pair-scenes.json'),{});c.save(path.join(root,'examples/manifest.json'),{counts:{pairExamples:0}});c.save(path.join(root,'package.json'),{version:'9.9.9-fixture'});fs.mkdirSync(path.join(root,'editorial'));const q=c.plan(root,{id:'fixture',maxBatches:1});assert.equal(q.publicVersion,'9.9.9-fixture');assert.deepEqual(q.batches[0].scenes.map(s=>s.exampleId),['S01-single-a','S01-single-b','S02-single-a','S02-single-b']);assert.ok(q.batches[0].scenes.every(s=>s.sourceHash===c.hash(f.beats)));assert.throws(()=>c.plan(root,{maxBatches:6}));assert.throws(()=>c.plan(root,{maxAttempts:0}));assert.throws(()=>c.plan(root,{maxMinutes:0}));});

function repositoryFixture(){const root=temp(),records={};for(let n=1;n<=12;n++){const key='S'+String(n).padStart(2,'0');records[key]={title:'Fixture '+key,instruction:'Use the explicit fixture behavior.',contentVersion:'1',examples:f.input().records.map((r,i)=>{const scene=structuredClone(r.before);scene.id=key+'-single-'+(i?'b':'a');if(i)scene.beats[0].text='I brought a second torn map to plan our walk.';return scene;})};}c.save(path.join(root,'examples/authoring/single-scenes.json'),{records});c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{}});c.save(path.join(root,'examples/authoring/pair-scenes.json'),{});c.save(path.join(root,'package.json'),{version:'9.9.9-fixture'});fs.mkdirSync(path.join(root,'editorial'));for(const file of ['AGENTS.md','CHECKPOINT-STATUS.md','docs/CODEX-HINT-AUDIT-HANDOFF.md','docs/COACH-REVIEW-RUBRIC.md']){fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),'Explicit artificial fixture, not a production review.');}fixtureBuild(root);return root;}
function fixtureBuild(root){const singles=c.read(path.join(root,'examples/authoring/single-scenes.json')).records;c.save(path.join(root,'examples/data/singles.fixture.json'),{records:Object.fromEntries(Object.entries(singles).map(([k,v])=>[k,v.examples]))});c.save(path.join(root,'examples/manifest.json'),{counts:{pairExamples:0},files:{singles:{plainUrl:'examples/data/singles.fixture.json'}}});}
function fixtureAdapters(root){const calls=[];return {root,calls,probe:()=>({version:'fixture-only; no Codex process'}),invoke:async({role,input,dir})=>{calls.push(role);let output;if(role==='writer'){output=f.writer(input);output.bindings=input.bindings.map(b=>({key:b.key,compatible:true,assessment:'FIXTURE ONLY: transfer fields and pair references inspected.'}));output.records[0].beats=structuredClone(output.records[0].beats);output.records[0].beats[4].text='I will bring my bicycle so we can ride home.';output.records[0].decision='revised';}else{output=f.review(input);output.bindings=input.bindings.map(b=>({key:b.key,compatible:true,assessment:'FIXTURE ONLY: transfer fields and pair references inspected.'}));}c.save(path.join(dir,role+'.json'),output);return {output,proof:{usage:[{input_tokens:10,output_tokens:5}],freshInvocation:true,outputHash:c.hash(output)}};},validate:async stage=>{fixtureBuild(stage);return ['build:examples','audit:all','test'].map(script=>({script,code:0,timedOut:false,fixture:true}));}};}
test('two-batch fixture stops after current, checkpoints one revision, resumes without redoing completed work',async()=>{const {run}=require('../tools/local-audit-runner.cjs'),root=repositoryFixture(),dir=path.join(root,'.audit-runs/fixture'),file=path.join(dir,'queue.json'),q=c.plan(root,{id:'fixture',maxBatches:2});q.guard=c.fingerprint(root);c.save(file,q);const adapters=fixtureAdapters(root),validate=adapters.validate;let validations=0;adapters.validate=async stage=>{validations++;if(validations===1)fs.writeFileSync(path.join(dir,'STOP_AFTER_CURRENT_BATCH'),'fixture stop');return validate(stage);};const first=await run(file,'fixture',true,adapters);assert.equal(first.stopReason,'stop-after-current-batch');assert.equal(first.completed,20);assert.equal(first.revised.length,1);assert.equal(first.retained.length,19);assert.equal(first.pending.length,4);assert.equal(adapters.calls.length,2);const before=c.read(file).batches[0];assert.equal(c.read(path.join(root,before.comparison)).mechanicallyChangedPairDialogue.length,0);fs.unlinkSync(path.join(dir,'STOP_AFTER_CURRENT_BATCH'));const second=await run(file,'fixture',true,adapters);assert.equal(second.stopReason,'bounded-queue-complete');assert.equal(second.completed,24);assert.equal(adapters.calls.length,4);const third=await run(file,'fixture',true,adapters);assert.equal(third.completed,24);assert.equal(adapters.calls.length,4);assert.equal(c.read(path.join(root,'package.json')).version,'9.9.9-fixture');assert.ok(!fs.existsSync(path.join(root,'releases')));});
test('fixture rejected second passes exhaust bounded retries without canonical edits or advancement',async()=>{const {run}=require('../tools/local-audit-runner.cjs'),root=repositoryFixture(),file=path.join(root,'.audit-runs/fixture/queue.json'),q=c.plan(root,{id:'fixture',maxBatches:2,maxAttempts:2});q.guard=c.fingerprint(root);c.save(file,q);const adapters=fixtureAdapters(root),invoke=adapters.invoke;adapters.invoke=async opts=>{const result=await invoke(opts);if(opts.role==='reviewer'){result.output.records[0].hardGates.b4CausesA5=false;result.output.records[0].accept=false;}return result;};const result=await run(file,'fixture',true,adapters);assert.equal(result.stopReason,'bounded-retries-exhausted');assert.equal(result.completed,0);assert.equal(result.failed.length,1);assert.equal(result.blocked.length,19);assert.equal(result.pending.length,23);assert.equal(adapters.calls.length,4);assert.deepEqual(c.fingerprint(root),q.guard);await run(file,'fixture',true,adapters);assert.equal(adapters.calls.length,4);});
test('failed fixture validation never integrates optimistic accepted reviews',async()=>{const {run}=require('../tools/local-audit-runner.cjs'),root=repositoryFixture(),file=path.join(root,'.audit-runs/fixture/queue.json'),q=c.plan(root,{id:'fixture',maxBatches:1});q.guard=c.fingerprint(root);c.save(file,q);const adapters=fixtureAdapters(root);adapters.validate=async()=>{throw Error('fixture audit failed');};const result=await run(file,'fixture',true,adapters);assert.equal(result.completed,0);assert.match(result.stopReason,/fixture audit failed/);assert.deepEqual(c.fingerprint(root),q.guard);assert.ok(c.read(file).batches[0].stage);});
test('queue follows exporter stance-before-drive order, not JSON object insertion order',()=>{const root=repositoryFixture(),file=path.join(root,'examples/authoring/single-scenes.json'),v=c.read(file);v.records={D01:{...v.records.S01,examples:v.records.S01.examples.map(s=>({...s,id:s.id.replace('S01','D01')}))},...v.records};c.save(file,v);assert.equal(c.discover(root).pendingKeys[0],'S01');assert.equal(c.discover(root).pendingKeys.at(-1),'D01');});
test('a conservative second-pass rejection is allowed without inflating scores',()=>{const i=f.input(),w=f.writer(i),ri=c.reviewerInput(i,w),r=f.review(ri);r.records[0].accept=false;c.validateReview(ri,r);assert.equal(c.allAccepted(w,r),false);});

test('actual failed writer excerpts retain strict citations and derive only arithmetic with provenance',()=>{
 const saved=require('./fixtures/local-audit-production-failures.json'),i=f.input(),w=f.writer(i);w.records[0].firstPass=saved.missingCitation;assert.throws(()=>c.validateWriter(i,w),/S01-single-a firstPass: cite numbered turns for relationship/);
 for(const [n,r] of saved.incorrectTotals.entries()){const draft=f.writer(i);draft.records[0].firstPass=structuredClone(r.firstPass);draft.records[0].decision='revised';draft.records[0].beats=structuredClone(draft.records[0].beats);draft.records[0].beats[4].text='I will bring my bicycle for the return journey.';assert.throws(()=>c.validateWriter(i,draft),/weightedTotal expected/);const derived=worker.deriveTotals(draft,'writer');assert.equal(derived.adjustments.length,1);assert.equal(derived.adjustments[0].to,[65,65][n]);assert.deepEqual(derived.output.records[0].firstPass.ratings,r.firstPass.ratings);assert.deepEqual(derived.output.records[0].beats,draft.records[0].beats);c.validateWriter(i,derived.output);}
 assert.match(worker.schemas.writer.properties.records.items.properties.firstPass.properties.ratings.properties.relationship.properties.evidence.description,/numbered dialogue turns/);
});

test('a persisted batch boundary blocks later batches on repeated resume',async()=>{const {run}=require('../tools/local-audit-runner.cjs'),root=repositoryFixture(),file=path.join(root,'.audit-runs/fixture/queue.json'),q=c.plan(root,{id:'fixture',maxBatches:2});q.guard=c.fingerprint(root);c.save(file,q);const adapters=fixtureAdapters(root);adapters.throughBatch='batch-001';const result=await run(file,'fixture',true,adapters);assert.equal(result.completed,20);assert.equal(result.stopReason,'batch-boundary-reached');assert.equal(adapters.calls.length,2);delete adapters.throughBatch;await run(file,'fixture',true,adapters);assert.equal(adapters.calls.length,2);assert.equal(c.read(file).batches[1].status,'pending');});
test('processing failures report stage and paths without declaring all scenes editorial failures',async()=>{const {run}=require('../tools/local-audit-runner.cjs'),root=repositoryFixture(),file=path.join(root,'.audit-runs/fixture/queue.json'),q=c.plan(root,{id:'fixture',maxBatches:1,maxAttempts:1});q.guard=c.fingerprint(root);c.save(file,q);const adapters=fixtureAdapters(root),invoke=adapters.invoke;adapters.invoke=async opts=>{const result=await invoke(opts);result.output.records[0].firstPass.ratings.relationship.evidence='B wants a less intrusive arrival and then advance notice.';return result;};const result=await run(file,'fixture',true,adapters);assert.equal(result.failed.length,0);assert.equal(result.blocked.length,20);assert.equal(result.pending.length,20);assert.equal(result.diagnostics[0].stage,'writer-validation');assert.match(result.diagnostics[0].error,/S01-single-a.*relationship/);assert.ok(result.diagnostics[0].paths.writer.stderr.endsWith('writer.stderr.log'));});
test('derived totals preserve raw evidence and detect any subsequent rating mutation',()=>{const dir=temp(),i=f.input(),output=f.writer(i);output.records[0].firstPass.weightedTotal=99;c.save(path.join(dir,'writer.json'),output);c.save(path.join(dir,'writer.proof.json'),{outputHash:c.hash(output)});const final=worker.finalizeTotals(dir,'writer');assert.deepEqual(c.read(path.join(dir,'writer.raw.json')),output);worker.verifyTotals(dir,'writer',final.output,final.proof);final.output.records[0].firstPass.ratings.relationship.score=4;assert.throws(()=>worker.verifyTotals(dir,'writer',final.output,final.proof));});

test('explicit recovery preserves exhausted attempts and budgets, checks evidence, and copies proven drafts',async()=>{
 const root=repositoryFixture(),dir=path.join(root,'.audit-runs/fixture'),file=path.join(dir,'queue.json'),q=c.plan(root,{id:'fixture',maxBatches:2,maxAttempts:2}),b=q.batches[0];q.guard=c.fingerprint(root);q.status='stopped';b.status='failed';b.attempts=[{id:'attempt-01',status:'failed',error:'old failure',usage:[{input_tokens:4}]},{id:'attempt-02',status:'failed',error:'weighted total'}];for(const scene of b.scenes){scene.status='failed';scene.attempts=2;}c.save(file,q);
 const input=c.writerInput(root,b),source=path.join(dir,b.id,'attempt-02'),adapters=fixtureAdapters(root),first=await adapters.invoke({role:'writer',input,dir:source});c.save(path.join(source,'writer.input.json'),input);c.save(path.join(source,'writer.proof.json'),{freshInvocation:true,toolsUsed:false,outputHash:c.hash(first.output)});
 const testDir=path.join(root,'.audit-runs/e2e-fixture'),small={...input,records:input.records.slice(0,2),bindings:input.bindings.slice(0,1)},tw=await adapters.invoke({role:'writer',input:small,dir:testDir}),ri=c.reviewerInput(small,tw.output),tr=await adapters.invoke({role:'reviewer',input:ri,dir:testDir});c.save(path.join(testDir,'writer.input.json'),small);for(const [role,out] of [['writer',tw.output],['reviewer',tr.output]])c.save(path.join(testDir,role+'.proof.json'),{freshInvocation:true,toolsUsed:false,outputHash:c.hash(out)});
 const evidenceFile=path.join(dir,'recovery-evidence.json'),evidence={batch:b.id,reason:'Explicit artificial fixture recovery authorization.',beforeGuard:q.guard,afterGuard:q.guard,reconciledFiles:[],endToEnd:{status:'passed',directory:testDir},reuseWriterDirectory:source};c.save(evidenceFile,evidence);const {recover}=require('../tools/local-audit/recovery.cjs');recover(file,b.id,evidenceFile,true);const after=c.read(file);assert.deepEqual(after.batches[0].attempts.slice(0,2),b.attempts);assert.deepEqual(after.limits,q.limits);assert.equal(after.batches[0].attempts.length,3);assert.equal(after.batches[0].recovery.startIndex,2);assert.equal(after.stopAfterBatch,'batch-001');assert.equal(after.batches[1].status,'pending');assert.ok(fs.existsSync(after.batches[0].recovery.snapshot));assert.equal(after.batches[0].scenes[0].attempts,2);assert.throws(()=>recover(file,b.id,evidenceFile,true));
});

test('authorized model context excludes unrelated repository files and preserves accepted correction work',()=>{const r=require('../tools/local-audit-runner.cjs');const text=r.context('/nonexistent-do-not-read');assert.ok(!text.includes('AGENTS.md'));assert.ok(!text.includes('S01-single'));const input=f.input(),writer=f.writer(input),review=f.review(c.reviewerInput(input,writer));review.records[0].accept=false;const request=r.correctionRequest(writer,review),candidate=structuredClone(writer);candidate.records[0].beats=structuredClone(candidate.records[0].beats);candidate.records[0].beats[4].text='I will bring my bicycle for the trip home.';r.validateCorrection(candidate,request);candidate.records[1].reason='Unrequested alteration of an accepted candidate.';assert.throws(()=>r.validateCorrection(candidate,request),/already accepted/);candidate.records[1]=structuredClone(writer.records[1]);candidate.records[0].firstPass.weightedTotal=99;assert.throws(()=>r.validateCorrection(candidate,request),/original review/);});

test('real recover-batch CLI entry exports the lock before synchronous recovery dispatch',()=>{const runner=path.resolve(__dirname,'../tools/local-audit-runner.cjs'),root=temp(),queue=path.resolve(__dirname,'../.audit-runs/cli-entry-'+require('node:crypto').randomUUID()+'.json');c.save(queue,{root,id:'cli-fixture',status:'ready'});try{const result=require('node:child_process').spawnSync(process.execPath,[runner,'recover-batch','--queue',queue,'--batch','batch-001','--evidence','unused','--exclusive-editor'],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(result.status,1);assert.match(result.stderr,/stopped/);assert.doesNotMatch(result.stderr,/lock is not a function|circular dependency/);assert.ok(!fs.existsSync(path.join(root,'.audit-runner.lock')));}finally{fs.unlinkSync(queue);}});

test('partial fresh review carries only accepted unchanged scenes and preserves rejection',()=>{const reuse=require('../tools/local-audit/review-reuse.cjs'),input=f.input(),prior=f.writer(input),review=f.review(c.reviewerInput(input,prior));review.records[0].accept=false;const writer=structuredClone(prior);writer.records[0].beats[4].text='I will bring a bicycle to ride home.';writer.records[0].decision='revised';const selected=reuse.plan(input,writer,prior,review);assert.equal(selected.input.records.filter(r=>!r.reference).length,1);assert.ok(!JSON.stringify(selected.input).includes('firstPass'));const partial=f.review(selected.input),combined=reuse.combine(input,writer,prior,review,partial);assert.equal(combined.output.records.length,2);assert.deepEqual(combined.output.records[1],review.records[1]);writer.records[1].beats[4].text='Changed accepted candidate without review.';assert.throws(()=>reuse.plan(input,writer,prior,review),/Accepted candidate changed/);});
test('carried review verification traces both raw invocations and rejects altered provenance',()=>{const reuse=require('../tools/local-audit/review-reuse.cjs'),base=temp(),old=path.join(base,'attempt-04'),dir=path.join(base,'attempt-05'),input=f.input(),prior=f.writer(input),review=f.review(c.reviewerInput(input,prior));review.records[0].accept=false;const writer=structuredClone(prior);writer.records[0].beats[4].text='I will take my bicycle so we can ride home.';writer.records[0].decision='revised';function artifacts(folder,role,output,modelInput){c.save(path.join(folder,role+'.json'),output);c.save(path.join(folder,role+'.proof.json'),{freshInvocation:true,toolsUsed:false,outputHash:c.hash(output)});c.save(path.join(folder,role+'.process.json'),{code:0,timedOut:false,command:['fixture-only','--sandbox','read-only','--ephemeral']});fs.writeFileSync(path.join(folder,role+'.stdout.log'),JSON.stringify({type:'turn.completed'})+'\n');c.save(path.join(folder,role+'.input.json'),role==='reviewer'?{...modelInput,records:modelInput.records.map(r=>({...r,candidateHash:c.hash(r.beats)}))}:modelInput);}
 artifacts(old,'writer',prior,input);artifacts(old,'reviewer',review,c.reviewerInput(input,prior));const selection=reuse.plan(input,writer,prior,review),partial=f.review(selection.input);artifacts(dir,'reviewer',partial,selection.input);reuse.saveCombined(dir,old,input,writer,partial,{usage:[]});assert.equal(reuse.verify(dir,input,writer).output.records.length,2);const meta=c.read(path.join(dir,'reviewer-reuse.json'));meta.previousReviewHash='tampered';c.save(path.join(dir,'reviewer-reuse.json'),meta);assert.throws(()=>reuse.verify(dir,input,writer));});

test('recovery allowance stays bounded without resetting original attempt limits',()=>{const root=repositoryFixture(),q=c.plan(root,{maxBatches:1,maxAttempts:2}),b=q.batches[0];b.recovery={startIndex:2,maxAttempts:4};assert.throws(()=>c.validateBounds(q),/capped at three/);b.recovery.maxAttempts=3;b.attempts=Array.from({length:5},()=>({status:'failed'}));c.validateBounds(q);assert.equal(q.limits.maxAttempts,2);b.attempts.push({status:'active'});assert.throws(()=>c.validateBounds(q),/budget exceeded/);});
test('separate editorial allowance targets only prior rejections and never changes original budget',()=>{const root=repositoryFixture(),q=c.plan(root,{id:'fixture',maxBatches:1,maxAttempts:2}),b=q.batches[0],input=f.input(),review=f.review(c.reviewerInput(input,f.writer(input)));review.records[0].accept=false;b.recovery={startIndex:2,maxAttempts:3};b.attempts=Array.from({length:5},(_,n)=>({id:'attempt-0'+(n+1),status:'rejected',critique:{review}}));b.editorialAllowance={startIndex:5,maxAttempts:2,authorizationHash:'fixture',snapshot:'fixture',reason:'Explicit fixture authorization for two targeted correction rounds',sceneIds:[review.records[0].exampleId]};assert.equal(c.attemptLimit(q,b),7);c.validateBounds(q);assert.equal(q.limits.maxAttempts,2);assert.equal(b.recovery.maxAttempts,3);b.editorialAllowance.maxAttempts=3;assert.throws(()=>c.validateBounds(q),/two rounds/);b.editorialAllowance.maxAttempts=2;b.editorialAllowance.sceneIds.push(review.records[1].exampleId);assert.throws(()=>c.validateBounds(q),/exactly the rejected/);});
test('two targeted review rounds retain a verified earlier reuse chain and reject stale ancestors',()=>{const reuse=require('../tools/local-audit/review-reuse.cjs'),base=temp(),input=f.input();let writer=f.writer(input),review=f.review(c.reviewerInput(input,writer));review.records[0].accept=false;function artifacts(dir,role,output,modelInput){c.save(path.join(dir,role+'.json'),output);c.save(path.join(dir,role+'.proof.json'),{freshInvocation:true,toolsUsed:false,outputHash:c.hash(output)});c.save(path.join(dir,role+'.process.json'),{code:0,timedOut:false,command:['fixture-only','read-only','--ephemeral']});fs.writeFileSync(path.join(dir,role+'.stdout.log'),JSON.stringify({type:'turn.completed'})+'\n');c.save(path.join(dir,role+'.input.json'),role==='reviewer'?{...modelInput,records:modelInput.records.map(r=>({...r,candidateHash:c.hash(r.beats)}))}:modelInput);}const first=path.join(base,'attempt-04');artifacts(first,'writer',writer,input);artifacts(first,'reviewer',review,c.reviewerInput(input,writer));let previous=first;for(const n of [5,6]){const dir=path.join(base,'attempt-0'+n),next=structuredClone(writer);next.records[0].beats[4].text=n===5?'I will bring my bicycle so we can ride home.':'I will bring two bicycles so we can ride home.';next.records[0].decision='revised';const plan=reuse.plan(input,next,writer,review),partial=f.review(plan.input);partial.records[0].accept=n===6;artifacts(dir,'writer',next,input);artifacts(dir,'reviewer',partial,plan.input);review=reuse.saveCombined(dir,previous,input,next,partial,{fixture:true}).output;assert.deepEqual(reuse.verify(dir,input,next).output,review);writer=next;previous=dir;}assert.ok(c.allAccepted(writer,review));c.save(path.join(first,'reviewer.json'),{});assert.throws(()=>reuse.verify(previous,input,writer));});


test('normal editorial policy separates technical failures and two corrections without resetting budgets',()=>{
 const policy=require('../tools/local-audit/editorial-policy.cjs'),q={limits:{maxAttempts:2}},b={correctionPolicy:{maxCorrections:2,authorizationHash:'fixture'},attempts:[]};
 assert.ok(policy.mayStart(q,b));b.attempts.push({status:'failed'});assert.ok(policy.mayStart(q,b));
 for(let n=0;n<3;n++)b.attempts.push({status:'rejected'});assert.equal(policy.mayStart(q,b),false);assert.equal(q.limits.maxAttempts,2);
 const boundary={stopAfterBatch:'batch-001',elapsedMs:100,limits:q.limits};policy.boundary(boundary,'batch-005');assert.equal(boundary.boundaryHistory[0].from,'batch-001');assert.equal(boundary.elapsedMs,100);
});
test('normal corrections preserve accepted reviews, stage exceptions and continue the next independent batch',async()=>{
 const root=repositoryFixture(),file=path.join(root,'.audit-runs/fixture/queue.json'),q=c.plan(root,{id:'fixture',maxBatches:2,maxAttempts:2});
 for(const b of q.batches)b.correctionPolicy={maxCorrections:2,authorizationHash:'fixture'};q.guard=c.fingerprint(root);c.save(file,q);
 const adapters=fixtureAdapters(root),base=adapters.invoke,reviewSizes=[];
 adapters.invoke=async opts=>{const result=await base(opts);if(opts.role==='writer'&&opts.corrections?.savedWriter){result.output=structuredClone(opts.corrections.savedWriter);result.output.records[0].beats[4].text='I will bring my bicycle so we can ride home together.';}
 if(opts.role==='reviewer'){reviewSizes.push(opts.input.records.filter(r=>!r.reference).length);if(opts.input.records.some(r=>r.exampleId==='S01-single-a'))result.output.records.find(r=>r.exampleId==='S01-single-a').accept=false;}
 const {dir,role,input}=opts,out=result.output;result.proof={...result.proof,toolsUsed:false,outputHash:c.hash(out)};c.save(path.join(dir,role+'.json'),out);c.save(path.join(dir,role+'.proof.json'),result.proof);c.save(path.join(dir,role+'.process.json'),{code:0,timedOut:false,command:['fixture-only','read-only','--ephemeral']});c.save(path.join(dir,role+'.input.json'),role==='reviewer'?{...input,records:input.records.map(r=>({...r,candidateHash:c.hash(r.beats)}))}:input);fs.writeFileSync(path.join(dir,role+'.stdout.log'),JSON.stringify({type:'turn.completed'})+'\n');return result;};
 const result=await require('../tools/local-audit-runner.cjs').run(file,'fixture',true,adapters),after=c.read(file);assert.deepEqual(reviewSizes,[20,1,1,4]);assert.equal(after.batches[0].status,'exception');assert.equal(after.batches[0].attempts.length,3);assert.equal(after.batches[1].status,'complete');assert.equal(result.acceptedStaged.length,19);assert.deepEqual(result.unresolved,['S01-single-a']);assert.equal(result.completed,4);assert.equal(result.stopReason,'configured-batch-limit-reached');assert.equal(c.discover(root).done.has('S01-single-b'),false);const calls=adapters.calls.length;await require('../tools/local-audit-runner.cjs').run(file,'fixture',true,adapters);assert.equal(adapters.calls.length,calls);
});


test('atomic queue save retries transient Windows sharing errors without deleting the checkpoint',()=>{const dir=temp(),file=path.join(dir,'queue.json');c.save(file,{prior:true});const original=fs.renameSync;let calls=0;try{fs.renameSync=(a,b)=>{calls++;if(calls<3){assert.deepEqual(c.read(file),{prior:true});throw Object.assign(Error('fixture sharing violation'),{code:'EPERM'});}return original(a,b);};c.save(file,{next:true});assert.equal(calls,3);assert.deepEqual(c.read(file),{next:true});}finally{fs.renameSync=original;}});


test('writer contract explains unchanged description gate and reports the exact failing scene',()=>{assert.match(worker.schemas.writer.properties.records.items.properties.confusableConcept.description,/At least 20/);const i=f.input(),w=f.writer(i);w.records[0].confusableConcept='Ordinary diligence.';assert.throws(()=>c.validateWriter(i,w),/S01-single-a confusableConcept.*minimum 20/);});
test('binding context includes only exact referenced seeds and their card instructions',()=>{const root=repositoryFixture();c.save(path.join(root,'examples/authoring/pair-scenes.json'),{'fixture-pair':[{id:'fixture-pair-a',seedRefs:['S01-single-a','S02-single-b']}]});const q=c.plan(root,{maxBatches:1}),i=c.writerInput(root,q.batches[0]),seeds=i.bindings.find(b=>b.key==='S01').supportingSeeds;assert.deepEqual(seeds.map(s=>s.scene.id),['S01-single-a','S02-single-b']);for(const s of seeds){assert.equal(s.card.instruction,'Use the explicit fixture behavior.');assert.equal(s.sourceHash,c.hash(s.scene));}assert.ok(!seeds.some(s=>s.card.id==='S03'));});
test('binding-only rejection saves accepted scenes without another editorial call',()=>{const policy=require('../tools/local-audit/editorial-policy.cjs'),i=f.input(),w=f.writer(i),review=f.review(c.reviewerInput(i,w)),q={limits:{maxAttempts:2}},b={correctionPolicy:{maxCorrections:2,authorizationHash:'fixture'},scenes:i.records.map(r=>({exampleId:r.exampleId,status:'active'})),attempts:[{id:'attempt-01',status:'rejected',critique:{review,writerBindingReservations:[{key:'S01',compatible:false,assessment:'Unresolved provenance remains pending.'}]}}]};assert.equal(policy.mayStart(q,b),false);const e=policy.exception(b);assert.equal(e.reason,'binding-provenance-blocked');assert.equal(e.acceptedStaged.length,2);assert.equal(e.bindingIssues.length,1);assert.equal(e.integrated,false);});
test('paused checkpoint still rejects any source drift and releases its lock',async()=>{const root=repositoryFixture(),q=c.plan(root,{maxBatches:1}),file=path.join(root,'.audit-runs/fixture/queue.json');q.status='stopped';q.guard=c.fingerprint(root);c.save(file,q);fs.writeFileSync(path.join(root,'unrelated.txt'),'Do not overwrite');await assert.rejects(require('../tools/local-audit/checkpoint.cjs').checkpoint(file,{'exclusive-editor':true}),/Checkpoint source drift/);assert.equal(fs.readFileSync(path.join(root,'unrelated.txt'),'utf8'),'Do not overwrite');assert.ok(!fs.existsSync(path.join(root,'.audit-runner.lock')));});


test('an actual CLI usage-limit error is non-isolatable and preserves its process logs',async()=>{const dir=temp();await assert.rejects(worker.invoke({executable:'fixture-only',role:'writer',input:f.input(),dir,rubricText:'fixture',timeoutMs:1000,runCommand:async(exe,args,cwd,log)=>{fs.writeFileSync(log+'.stdout.log',JSON.stringify({type:'error',message:"You've hit your usage limit"})+'\n');fs.writeFileSync(log+'.stderr.log','');return {code:1,timedOut:false};}}),e=>e.nonIsolatable===true&&/Codex usage/.test(e.message));assert.ok(fs.readFileSync(path.join(dir,'writer.stdout.log'),'utf8').includes('usage limit'));});
test('non-isolatable worker limits stop before any retry or later batch',async()=>{const root=repositoryFixture(),file=path.join(root,'.audit-runs/fixture/queue.json'),q=c.plan(root,{maxBatches:2});for(const b of q.batches)b.correctionPolicy={maxCorrections:2,authorizationHash:'fixture'};q.guard=c.fingerprint(root);c.save(file,q);const adapters=fixtureAdapters(root);let calls=0;adapters.invoke=async()=>{calls++;throw Object.assign(Error('fixture usage limit'),{nonIsolatable:true});};const result=await require('../tools/local-audit-runner.cjs').run(file,'fixture',true,adapters);assert.equal(calls,1);assert.equal(result.stopReason,'fixture usage limit');assert.equal(c.read(file).batches[1].status,'pending');});

const perExample=require('../tools/local-audit/per-example.cjs');
test('per-example selection keeps accepted companion, blocks only affected bindings, and never accepts a rejection',()=>{
 const input=f.input(),writer=f.writer(input);writer.records[0].beats=structuredClone(writer.records[0].beats);writer.records[0].beats[4].text='I will bring my bicycle so we can ride home.';writer.records[0].decision='revised';const review=f.review(c.reviewerInput(input,writer));review.records[1].accept=false;
 assert.deepEqual(perExample.selection(input,writer,review).eligible,['S01-single-a']);assert.throws(()=>perExample.assertSelection(input,writer,review,['S01-single-b']),/Unaccepted/);
 review.bindings[0].compatible=false;assert.equal(perExample.selection(input,writer,review).staged.length,1);assert.equal(perExample.selection(input,writer,review).eligible.length,0);
 review.bindings[0].compatible=true;review.records[0].candidateHash='stale';assert.throws(()=>perExample.selection(input,writer,review),/different dialogue/);
});
test('mixed-result atomic integration recovers interruption without changing rejected text or claiming batch completion',async()=>{
 const root=repositoryFixture(),q=c.plan(root,{maxBatches:1}),b=q.batches[0],queueFile=path.join(root,'.audit-runs/test/queue.json');b.keys=['S01'];b.scenes=b.scenes.filter(s=>s.key==='S01');q.guard=c.fingerprint(root);
 const input=c.writerInput(root,b),writer=f.writer(input);writer.records[0].beats=structuredClone(writer.records[0].beats);writer.records[0].beats[4].text='I will bring my bicycle so we can ride home.';writer.records[0].decision='revised';const review=f.review(c.reviewerInput(input,writer));review.records[1].accept=false;
 const evidence={attempt:'attempt-01',input,writer,review,firstProof:{fixture:true},secondProof:{fixture:true}},adapters={evidence,validate:fixtureAdapters(root).validate,interruptAfter:1};c.save(queueFile,q);
 await assert.rejects(perExample.integrate(q,b,queueFile,Date.now()+60000,adapters),/Fixture interruption/);assert.ok(b.pendingIntegration);assert.equal(c.discover(root).single.S01.examples[1].beats[0].text,input.records[1].before.beats[0].text);
 await perExample.integrate(q,b,queueFile,Date.now()+60000);assert.equal(b.status,'partial');assert.equal(b.partialTerminal,true);assert.deepEqual(b.remainingSceneIds,['S01-single-b']);assert.equal(c.discover(root).progress.singlesReviewed,1);assert.deepEqual(c.discover(root).single.S01.examples[1],input.records[1].before);perExample.verifyGroups(q,b);
 assert.deepEqual(await perExample.integrate(q,b,queueFile,Date.now()+60000,{evidence}),[]);assert.equal(b.integrationGroups.length,1);
});
test('accepted retention integrates its evidence without rewriting either dialogue',async()=>{
 const root=repositoryFixture(),q=c.plan(root,{maxBatches:1}),b=q.batches[0];b.keys=['S01'];b.scenes=b.scenes.filter(s=>s.key==='S01');q.guard=c.fingerprint(root);const input=c.writerInput(root,b),writer=f.writer(input),review=f.review(c.reviewerInput(input,writer));review.records[1].accept=false;
 await perExample.integrate(q,b,path.join(root,'.audit-runs/test/queue.json'),Date.now()+60000,{evidence:{attempt:'attempt-01',input,writer,review},validate:fixtureAdapters(root).validate});assert.equal(b.scenes[0].status,'retained');assert.deepEqual(c.discover(root).single.S01.examples,input.records.map(r=>r.before));assert.equal(c.discover(root).progress.singlesReviewed,1);
});

test('binding conflicts remain pending while exact accepted retentions change no seeds or transfers',async()=>{
 const root=repositoryFixture(),q=c.plan(root,{maxBatches:1}),b=q.batches[0];b.keys=['S01'];b.scenes=b.scenes.filter(s=>s.key==='S01');q.guard=c.fingerprint(root);
 const input=c.writerInput(root,b),writer=f.writer(input);writer.records[1].beats=structuredClone(writer.records[1].beats);writer.records[1].beats[4].text='I will bring my bicycle so we can ride home.';writer.records[1].decision='revised';
 const review=f.review(c.reviewerInput(input,writer));writer.bindings[0].compatible=false;review.bindings[0].compatible=false;
 const before=c.hash(c.read(path.join(root,'examples/authoring/stance-transfers.json'))),selection=perExample.selection(input,writer,review);
 assert.deepEqual(selection.eligible,['S01-single-a']);assert.deepEqual(selection.staged.map(s=>s.exampleId),['S01-single-b']);
 await perExample.integrate(q,b,path.join(root,'.audit-runs/test/queue.json'),Date.now()+60000,{evidence:{attempt:'attempt-01',input,writer,review},validate:fixtureAdapters(root).validate});
 assert.equal(b.scenes[0].status,'retained');assert.equal(b.scenes[1].status,'accepted-staged');assert.deepEqual(c.discover(root).single.S01.examples,input.records.map(r=>r.before));assert.equal(c.hash(c.read(path.join(root,'examples/authoring/stance-transfers.json'))),before);assert.equal(writer.bindings[0].compatible,false);assert.equal(review.bindings[0].compatible,false);
});

test('a later accepted companion follows an explicit completed seed amendment rather than refreshing hashes blindly',async()=>{
 const root=repositoryFixture(),scenes=c.read(path.join(root,'examples/authoring/single-scenes.json')).records.S01.examples;c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S01:{seedBindingHashes:scenes.map(s=>c.hash(s.beats)),opening:'Fixture unchanged template'}}});
 const q=c.plan(root,{maxBatches:1}),b=q.batches[0],file=path.join(root,'.audit-runs/test/queue.json');b.keys=['S01'];b.scenes=b.scenes.filter(s=>s.key==='S01');q.guard=c.fingerprint(root);const input=c.writerInput(root,b),writer=f.writer(input);writer.records[0].beats=structuredClone(writer.records[0].beats);writer.records[0].beats[4].text='I will bring my bicycle so we can ride home.';writer.records[0].decision='revised';let review=f.review(c.reviewerInput(input,writer));review.records[1].accept=false;
 await perExample.integrate(q,b,file,Date.now()+60000,{evidence:{attempt:'attempt-01',input,writer,review},validate:fixtureAdapters(root).validate});
 const corrected=structuredClone(writer);corrected.records[1].beats[4].text='Then I will cycle beside you on our way home.';corrected.records[1].decision='revised';review=f.review(c.reviewerInput(input,corrected));
 const before=perExample.transferBase(root,input.bindings[0],corrected);assert.equal(before.priorIntegratedSeedAmendments.length,1);const bad=structuredClone(input.bindings[0]);bad.transfer.opening='Unrelated transfer change';assert.throws(()=>perExample.transferBase(root,bad,corrected),/wording changed/);
 await perExample.integrate(q,b,file,Date.now()+60000,{evidence:{attempt:'attempt-02',input,writer:corrected,review},validate:fixtureAdapters(root).validate});assert.equal(b.status,'complete');assert.equal(b.integrationGroups.length,2);require('../tools/local-audit-runner.cjs').verifyCompleted(q,b);assert.equal(c.discover(root).progress.singlesReviewed,2);
});

test('partial summary separates integrated status from the preserved historical exception',()=>{const b={id:'batch',status:'partial',scenes:[{exampleId:'S01-single-a',status:'revised',acceptedHash:'verified'},{exampleId:'S01-single-b',status:'unresolved'}],attempts:[],exception:{acceptedStaged:['S01-single-a'],unresolved:['S01-single-b']}};const result=c.summary({id:'fixture',batches:[b]});assert.deepEqual(result.exceptions[0].acceptedStaged,[]);assert.deepEqual(result.exceptions[0].integratedSceneIds,['S01-single-a']);assert.deepEqual(b.exception.acceptedStaged,['S01-single-a']);});
test('stop-after-current control prevents starting saved exception integration',async()=>{const root=repositoryFixture(),q=c.plan(root,{maxBatches:1}),dir=path.join(root,'.audit-runs/test'),file=path.join(dir,'queue.json');q.batches[0].status='exception';q.perExamplePolicy={acceptance:'per-example'};q.guard=c.fingerprint(root);c.save(file,q);fs.writeFileSync(path.join(dir,'STOP_AFTER_CURRENT_BATCH'),'fixture');const adapters=fixtureAdapters(root),result=await require('../tools/local-audit-runner.cjs').run(file,'fixture',true,adapters);assert.equal(result.stopReason,'stop-after-current-batch');assert.equal(adapters.calls.length,0);});

test('observed reconnect notices require completed matching output and preserve every event',()=>{
 const output={fixture:'completed'},retry={type:'error',message:'Reconnecting... 3/5 (stream disconnected before completion: No such host is known. (os error 11001))'},message={type:'item.completed',item:{type:'agent_message',text:JSON.stringify(output)}},done={type:'turn.completed'},events=[retry,message,done];
 assert.deepEqual(worker.validateEvents(events,output),[retry]);assert.equal(events.length,3);
 for(const bad of [[retry,message],[retry,message,done,retry],[retry,{type:'turn.failed'},message,done],[{type:'error',message:'permission denied'},message,done],[{type:'error',message:'Reconnecting... 1/5 (approval required)'},message,done],[retry,{type:'item.completed',item:{type:'command_execution'}},message,done]])assert.throws(()=>worker.validateEvents(bad,output));
 assert.throws(()=>worker.validateEvents(events,{fixture:'different'}));
});

test('saved invocation uses the same strict completed-reconnect proof gate as a live worker',()=>{
 const reuse=require('../tools/local-audit/review-reuse.cjs'),dir=temp(),output=f.writer(f.input());
 const retry={type:'error',message:'Reconnecting... 1/5 (request timed out)'},message={type:'item.completed',item:{type:'agent_message',text:JSON.stringify(output)}},done={type:'turn.completed'};
 c.save(path.join(dir,'writer.json'),output);c.save(path.join(dir,'writer.proof.json'),{freshInvocation:true,toolsUsed:false,outputHash:c.hash(output)});c.save(path.join(dir,'writer.process.json'),{code:0,timedOut:false,command:['fixture','read-only','--ephemeral']});
 const log=events=>fs.writeFileSync(path.join(dir,'writer.stdout.log'),events.map(JSON.stringify).join('\n'));
 log([retry,message,done]);assert.deepEqual(reuse.invocation(dir,'writer').output,output);
 for(const events of [[retry,message],[retry,{type:'turn.failed'},message,done],[{type:'error',message:'permission denied'},message,done],[retry,{type:'item.completed',item:{type:'command_execution'}},message,done],[retry,{...message,item:{...message.item,text:'{}'}},done]]){log(events);assert.throws(()=>reuse.invocation(dir,'writer'));}
});
test('saved subset integration does not retire an interrupted correction with remaining original allowance',()=>{
 const pe=require('../tools/local-audit/per-example.cjs'),q={limits:{maxAttempts:2}},b={correctionPolicy:{maxCorrections:2,authorizationHash:'fixture'},attempts:[{status:'rejected',critique:{review:{records:[{accept:false}]}}},{status:'rejected',critique:{review:{records:[{accept:false}]}}},{status:'failed',error:'writer process failure timedOut=true'}]};
 assert.equal(pe.interruptedCorrection(q,b),true);b.attempts.push({status:'failed',error:'writer timedOut=true'});assert.equal(pe.interruptedCorrection(q,b),false);b.attempts.pop();b.attempts.push({status:'rejected',critique:{review:{records:[{accept:false}]}}});assert.equal(pe.interruptedCorrection(q,b),false);
});

test('context-only S67 binding recovery preserves every scene review and unrelated hold',()=>{
 const br=require('../tools/local-audit/binding-recovery.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S67')),writer=f.writer(input);writer.bindings[0].key='S67';writer.bindings[0].compatible=false;
 const pairs=['a','b'].map((v,n)=>({id:'S67+D101-'+v,seedRefs:['S67-single-'+v,'D101-single-'+v],seedUse:'FIXTURE exact routing and delegated beginning.',beats:input.records[n].before.beats}));input.bindings[0].bespokePairs=pairs;
 const supportingSeeds=pairs.flatMap((p,n)=>p.seedRefs.map(id=>({card:{id:id.split('-single-')[0],instruction:'FIXTURE exact supporting instruction.'},scene:{...input.records[n].before,id},sourceHash:c.hash({...input.records[n].before,id})})));
 input.bindings.push({key:'S61',transfer:null,bespokePairs:[]});writer.bindings.push({key:'S61',assessment:'FIXTURE unrelated persistent transfer finding.',compatible:false});const review=f.review(c.reviewerInput(input,writer));review.bindings=writer.bindings.map(b=>({...b}));review.records[0].accept=false;
 const spec={bindingKey:'S67',selectedIds:['S67-single-b'],changes:[],supportingSeeds,pairRecordHashes:Object.fromEntries(pairs.map(p=>[p.id,c.hash(p)])),authorAssessment:'FIXTURE A1 preserves routing with exact missing source context.'},partial={records:[],bindings:[{key:'S67',compatible:true,assessment:'FIXTURE exact supporting sources preserve A1 routing.'}]};
 const result=br.derive(input,writer,review,spec,partial);assert.deepEqual(result.writer.records,writer.records);assert.deepEqual(result.review.records,review.records);assert.deepEqual(result.writer.bindings[1],writer.bindings[1]);assert.deepEqual(result.input.bindings[0].bespokePairs,pairs);assert.equal(result.review.records[0].accept,false);
 assert.throws(()=>br.derive(input,writer,review,{...spec,supportingSeeds:[]},partial));assert.throws(()=>br.derive(input,writer,review,{...spec,selectedIds:['S63-single-b']},partial));assert.throws(()=>br.derive(input,writer,review,spec,{records:[],bindings:[{...partial.bindings[0],compatible:false}]}));review.records[1].accept=false;assert.throws(()=>br.derive(input,writer,review,spec,partial),/unresolved selected dialogue/);
});
test('explicit completed-writer recovery preserves original bytes and rejects stale source or unknown errors',()=>{
 const transport=require('../tools/local-audit/transport-recovery.cjs'),source=temp(),input=f.input(),output=f.writer(input),schema=path.join(source,'schema.json');c.save(schema,worker.schemas.writer);c.save(path.join(source,'writer.json'),output);c.save(path.join(source,'writer.input.json'),input);c.save(path.join(source,'writer.process.json'),{code:0,timedOut:false,elapsedMs:1,log:'fixture-original',command:['fixture','read-only','--ephemeral','--output-schema',schema]});fs.writeFileSync(path.join(source,'writer.prompt.txt'),worker.prompt('writer',input,'FIXTURE rubric','FIXTURE context',null));
 const retry={type:'error',message:'Reconnecting... 1/5 (request timed out)'},events=[retry,{type:'item.completed',item:{type:'agent_message',text:JSON.stringify(output)}},{type:'turn.completed',usage:{input_tokens:1,output_tokens:1}}];fs.writeFileSync(path.join(source,'writer.stdout.log'),events.map(JSON.stringify).join('\n'));
 const before=c.sha(fs.readFileSync(path.join(source,'writer.json'))),dest=path.join(temp(),'recovered');const result=transport.recoverCompletedWriter(source,dest,input);assert.deepEqual(result.output,output);assert.equal(c.sha(fs.readFileSync(path.join(source,'writer.json'))),before);assert.equal(fs.existsSync(path.join(source,'writer.proof.json')),false);assert.throws(()=>transport.recoverCompletedWriter(source,dest,input),/already exists/);assert.throws(()=>transport.recoverCompletedWriter(source,path.join(temp(),'stale'),{...input,extra:'drift'}),/source drift/);events[0].message='permission denied';fs.writeFileSync(path.join(source,'writer.stdout.log'),events.map(JSON.stringify).join('\n'));assert.throws(()=>transport.recoverCompletedWriter(source,path.join(temp(),'unknown'),input),/Worker reported failure/);
});

test('explicit provenance amendments preserve dialogue, scores, unrelated holds and rejection status',()=>{
 const br=require('../tools/local-audit/binding-recovery.cjs'),pa=require('../tools/local-audit/provenance-amendment.cjs');
 const input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S111')),writer=f.writer(input);writer.bindings[0].key='S111';writer.bindings[0].compatible=false;
 const pairs=['a','b'].map((v,n)=>({id:'S111+D103-'+v,seedRefs:['S111-single-'+v,'D103-single-'+v],seedUse:'FIXTURE attribution before repair.',beats:input.records[n].before.beats,exampleVersion:'fixture',editorialStatus:'pending'}));input.bindings[0].bespokePairs=pairs;
 const seeds=pairs.flatMap((p,n)=>p.seedRefs.map(id=>({card:{id:id.split('-single-')[0],instruction:'FIXTURE exact supporting instruction.'},scene:{...input.records[n].before,id},sourceHash:c.hash({...input.records[n].before,id})})));
 input.bindings.push({key:'S61',transfer:null,bespokePairs:[]});writer.bindings.push({key:'S61',assessment:'FIXTURE unrelated transfer remains incompatible.',compatible:false});const review=f.review(c.reviewerInput(input,writer));review.bindings=writer.bindings.map(b=>({...b}));review.records[0].accept=false;
 const p=pairs[1],after={...p,seedRefs:['S111-single-b','D103-single-a'],seedUse:'FIXTURE corrected attribution to the supplied first Drive seed.'},change={exampleId:p.id,beforeSeedUse:p.seedUse,afterSeedUse:after.seedUse,beforeSeedRefs:p.seedRefs,afterSeedRefs:after.seedRefs,beforeRecordHash:c.hash(p),afterRecordHash:c.hash(after),reason:'FIXTURE demonstrated crossed alternative references.'};
 const spec={schema:2,selectedIds:['S111-single-b'],repairs:[{key:'S111',changes:[change],supportingSeeds:seeds,authorAssessment:'FIXTURE A1 uses the exact cited seed; dialogue is preserved.'}]},fresh={records:[],bindings:[{key:'S111',compatible:true,assessment:'FIXTURE A1 source attribution agrees with the exact seeds.'}]};
 const result=br.derive(input,writer,review,spec,fresh);assert.deepEqual(result.writer.records,writer.records);assert.deepEqual(result.review.records,review.records);assert.deepEqual(result.writer.bindings[1],writer.bindings[1]);assert.equal(result.review.records[0].accept,false);assert.deepEqual(result.input.bindings[0].bespokePairs[1].beats,p.beats);assert.deepEqual(result.input.bindings[0].bespokePairs[1].seedRefs,after.seedRefs);
 assert.equal(JSON.stringify(br.blind(input,writer,spec)).includes('firstPass'),false);assert.equal(JSON.stringify(br.blind(input,writer,spec)).includes('authorAssessment'),false);
 assert.throws(()=>br.derive(input,writer,review,{...spec,selectedIds:['S111-single-a']},fresh),/Unresolved selected/);
 assert.throws(()=>br.derive(input,writer,review,spec,{records:[],bindings:[{...fresh.bindings[0],compatible:false}]}),/rejected/);
 const bad=structuredClone(spec);bad.repairs[0].supportingSeeds=[];assert.throws(()=>br.blind(input,writer,bad),/Missing exact/);
 assert.throws(()=>pa.changedPairs(pairs,[{...change,afterSeedRefs:['S112-single-a','D103-single-a']}]),/Cross-card/);
 assert.throws(()=>pa.changedPairs(pairs,[{...change,afterRecordHash:c.hash({...after,beats:[]})}]),/after-record/);
 assert.throws(()=>pa.changedPairs(pairs,[{...change,afterBeats:[]}]),/deep/);
 assert.throws(()=>pa.changedPairs([{...p,seedUse:'Changed after review'}],[change]),/before-record/);
 assert.throws(()=>br.blind(input,writer,{...spec,repairs:[{...spec.repairs[0],key:'S06'}]}),/Undemonstrated/);
 const beforeRoot=temp(),afterRoot=temp(),pairFile='examples/authoring/pair-scenes.json',doc={records:{'S111+D103':pairs,'S06+D49':[{id:'S06+D49-b',seedUse:'FIXTURE pending mismatch remains untouched.',beats:[]}]}};
 c.save(path.join(beforeRoot,pairFile),doc);c.save(path.join(afterRoot,pairFile),doc);br.applySource(afterRoot,spec);c.save(path.join(afterRoot,'editorial/local-fixture/binding-recovery.json'),spec);br.assertSourceChange(beforeRoot,afterRoot,'editorial/local-fixture');br.assertApplied(afterRoot,spec);
 const applied=c.read(path.join(afterRoot,pairFile));assert.deepEqual(applied.records['S06+D49'],doc.records['S06+D49']);assert.deepEqual(applied.records['S111+D103'].map(p=>p.beats),pairs.map(p=>p.beats));applied.records['S111+D103'][1].beats=[];c.save(path.join(afterRoot,pairFile),applied);assert.throws(()=>br.assertApplied(afterRoot,spec),/Applied provenance/);assert.throws(()=>br.assertSourceChange(beforeRoot,afterRoot,'editorial/local-fixture'),/Only explicit/);
 const generatedBefore={id:p.id,beats:p.beats,seedRefs:p.seedRefs,editorialStatus:'pair-review-pending'},generatedAfter={...generatedBefore,seedRefs:change.afterSeedRefs};pa.assertReferenceChange(generatedBefore,generatedAfter,change);assert.throws(()=>pa.assertReferenceChange(generatedBefore,generatedAfter),/Unrelated/);assert.throws(()=>pa.assertReferenceChange(generatedBefore,{...generatedAfter,editorialStatus:'internal-second-pass'},change),/more than/);assert.throws(()=>pa.assertReferenceChange(generatedBefore,{...generatedAfter,beats:[]},change),/more than/);
 assert.throws(()=>pa.referenceAmendments(beforeRoot,afterRoot,[],['../elsewhere']),/Invalid provenance/);
 // Fixture-only complete proof round trip: the comparison accepts only the
 // exact reviewed reference amendment, never an optimistic metadata summary.
 c.save(path.join(afterRoot,pairFile),doc);br.applySource(afterRoot,spec);const folder='editorial/local-fixture',bundle=path.join(afterRoot,folder),fullSpec={...spec,originalAttempt:'attempt-01',reviewDirectory:'binding-review-01',originalInputHash:c.hash(input),originalWriterHash:c.hash(writer),originalReviewHash:c.hash(review)};
 function proof(dir,role,output,modelInput){c.save(path.join(dir,role+'.json'),output);c.save(path.join(dir,role+'.input.json'),modelInput);c.save(path.join(dir,role+'.proof.json'),{freshInvocation:true,toolsUsed:false,outputHash:c.hash(output)});c.save(path.join(dir,role+'.process.json'),{code:0,timedOut:false,command:['FIXTURE-ONLY','read-only','--ephemeral']});fs.writeFileSync(path.join(dir,role+'.stdout.log'),[{type:'item.completed',item:{type:'agent_message',text:JSON.stringify(output)}},{type:'turn.completed'}].map(JSON.stringify).join('\n'));fs.writeFileSync(path.join(dir,role+'.prompt.txt'),worker.prompt(role,modelInput,'FIXTURE rubric','FIXTURE context',null));}
 proof(path.join(bundle,'attempts/attempt-01'),'writer',writer,input);proof(path.join(bundle,'attempts/attempt-01'),'reviewer',review,c.reviewerInput(input,writer));proof(path.join(bundle,'binding-review-01'),'reviewer',fresh,br.blind(input,writer,fullSpec));c.save(path.join(bundle,'binding-recovery.json'),fullSpec);for(const [key,value]of Object.entries(result))c.save(path.join(bundle,'effective-'+key+'.json'),value);br.verify(bundle,{specHash:c.hash(fullSpec)});
 for(const [repo,pair]of [[beforeRoot,generatedBefore],[afterRoot,generatedAfter]]){c.save(path.join(repo,'examples/manifest.json'),{files:{all:{plainUrl:'examples/data/fixture.json'}}});c.save(path.join(repo,'examples/data/fixture.json'),{records:{singles:input.records.map(r=>r.before),pair:[pair]}});}
 assert.throws(()=>c.compareDataset(beforeRoot,afterRoot,spec.selectedIds),/Unrelated generated/);const comparison=c.compareDataset(beforeRoot,afterRoot,spec.selectedIds,folder);assert.deepEqual(comparison.otherRecordChanges,[p.id]);assert.equal(comparison.mechanicallyChangedPairDialogue.length,0);assert.equal(comparison.unchangedDialogue,3);
 c.save(path.join(bundle,'binding-review-01/reviewer.json'),{...fresh,bindings:[{...fresh.bindings[0],compatible:false}]});assert.throws(()=>c.compareDataset(beforeRoot,afterRoot,spec.selectedIds,folder));
});

test('explicit transfer amendments freeze scene reviews and reject metadata, slot and source drift',()=>{
 const t=require('../tools/local-audit/transfer-amendment.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S95'));
 const before={cardId:'S95',fingerprint:'FIXTURE fingerprint',seedIds:['S95-single-a','S95-single-b'],seedBindingHashes:input.records.map(r=>c.hash(r.before.beats)),reviewStatus:'compiled-pair-draft',action:'FIXTURE I hold {prop}.',opening:'FIXTURE opening. {request}',response:'FIXTURE response. {counter}',challenge:'FIXTURE challenge.',closing:'FIXTURE closing.'};input.bindings[0].transfer=before;
 const writer=f.writer(input);writer.bindings=[{key:'S95',compatible:false,assessment:'FIXTURE demonstrated transfer wording mismatch.'}];const review=f.review(c.reviewerInput(input,writer));review.bindings=structuredClone(writer.bindings);
 const after={...before,response:'FIXTURE amended response. {counter}'},spec={schema:3,key:'S95',selectedIds:before.seedIds,beforeTransfer:before,beforeTransferHash:c.hash(before),afterTransfer:after,afterTransferHash:c.hash(after),authorAssessment:'FIXTURE ONLY A1 and A3 source correspondence; no production rating or editorial claim.'};
 const blind=t.blind(input,writer,spec);assert.deepEqual(blind.records,[]);assert.ok(!JSON.stringify(blind).includes('weightedTotal'));const binding={records:[],bindings:[{key:'S95',compatible:true,assessment:'FIXTURE ONLY verified body correspondence, no individual pair approval.'}]};
 const effective=t.derive(input,writer,review,spec,binding);assert.deepEqual(effective.writer.records,writer.records);assert.deepEqual(effective.review.records,review.records);assert.deepEqual(effective.input,input);
 for(const field of ['cardId','fingerprint','reviewStatus','seedIds','seedBindingHashes']){const bad=structuredClone(spec);bad.afterTransfer[field]='tampered';bad.afterTransferHash=c.hash(bad.afterTransfer);assert.throws(()=>t.scope(bad));}
 const slot=structuredClone(spec);slot.afterTransfer.response='FIXTURE lost counter slot';slot.afterTransferHash=c.hash(slot.afterTransfer);assert.throws(()=>t.scope(slot),/slots/);
 assert.throws(()=>t.scope({...spec,key:'S06'}),/scope/);assert.throws(()=>t.derive(input,writer,review,spec,{records:[],bindings:[{...binding.bindings[0],compatible:false}]}),/rejected/);
 const root=temp(),expected=t.expectedApplied(spec,writer);c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S95:{...before,seedBindingHashes:expected.seedBindingHashes}}});c.save(path.join(root,'examples/authoring/single-scenes.json'),{records:{S95:{examples:writer.records.map(w=>({id:w.exampleId,beats:w.beats}))}}});t.applySource(root,spec,writer);t.assertApplied(root,spec);
 const drift=c.read(path.join(root,'examples/authoring/stance-transfers.json'));drift.records.S95.closing='Unreviewed change';c.save(path.join(root,'examples/authoring/stance-transfers.json'),drift);assert.throws(()=>t.assertApplied(root,spec),/differs/);
});

test('S61 demonstrated transfer amendments freeze scene reviews and reject metadata, slot and source drift',()=>{
 const t=require('../tools/local-audit/transfer-amendment.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S61'));
 const before={cardId:'S61',fingerprint:'FIXTURE fingerprint',seedIds:['S61-single-a','S61-single-b'],seedBindingHashes:input.records.map(r=>c.hash(r.before.beats)),reviewStatus:'compiled-pair-draft',action:'FIXTURE I hold {prop}.',opening:'FIXTURE opening. {request}',response:'FIXTURE response. {counter}',challenge:'FIXTURE challenge.',closing:'FIXTURE closing.'};input.bindings[0].transfer=before;
 const writer=f.writer(input);writer.bindings=[{key:'S61',compatible:false,assessment:'FIXTURE demonstrated transfer wording mismatch.'}];const review=f.review(c.reviewerInput(input,writer));review.bindings=structuredClone(writer.bindings);
 const after={...before,response:'FIXTURE amended response. {counter}'},spec={schema:3,key:'S61',selectedIds:before.seedIds,beforeTransfer:before,beforeTransferHash:c.hash(before),afterTransfer:after,afterTransferHash:c.hash(after),authorAssessment:'FIXTURE ONLY A1 and A3 source correspondence; no production rating or editorial claim.'};
 const blind=t.blind(input,writer,spec);assert.deepEqual(blind.records,[]);assert.ok(!JSON.stringify(blind).includes('weightedTotal'));const binding={records:[],bindings:[{key:'S61',compatible:true,assessment:'FIXTURE ONLY verified body correspondence, no individual pair approval.'}]};
 const effective=t.derive(input,writer,review,spec,binding);assert.deepEqual(effective.writer.records,writer.records);assert.deepEqual(effective.review.records,review.records);assert.deepEqual(effective.input,input);
 for(const field of ['cardId','fingerprint','reviewStatus','seedIds','seedBindingHashes']){const bad=structuredClone(spec);bad.afterTransfer[field]='tampered';bad.afterTransferHash=c.hash(bad.afterTransfer);assert.throws(()=>t.scope(bad));}
 const slot=structuredClone(spec);slot.afterTransfer.response='FIXTURE lost counter slot';slot.afterTransferHash=c.hash(slot.afterTransfer);assert.throws(()=>t.scope(slot),/slots/);
 assert.throws(()=>t.scope({...spec,key:'S06'}),/scope/);assert.throws(()=>t.derive(input,writer,review,spec,{records:[],bindings:[{...binding.bindings[0],compatible:false}]}),/rejected/);
 const root=temp(),expected=t.expectedApplied(spec,writer);c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S61:{...before,seedBindingHashes:expected.seedBindingHashes}}});c.save(path.join(root,'examples/authoring/single-scenes.json'),{records:{S61:{examples:writer.records.map(w=>({id:w.exampleId,beats:w.beats}))}}});t.applySource(root,spec,writer);t.assertApplied(root,spec);
 const drift=c.read(path.join(root,'examples/authoring/stance-transfers.json'));drift.records.S61.closing='Unreviewed change';c.save(path.join(root,'examples/authoring/stance-transfers.json'),drift);assert.throws(()=>t.assertApplied(root,spec),/differs/);
});


test('S131 demonstrated transfer amendments freeze scene reviews and reject metadata, slot and source drift',()=>{
 const t=require('../tools/local-audit/transfer-amendment.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S131'));
 const before={cardId:'S131',fingerprint:'FIXTURE fingerprint',seedIds:['S131-single-a','S131-single-b'],seedBindingHashes:input.records.map(r=>c.hash(r.before.beats)),reviewStatus:'compiled-pair-draft',action:'FIXTURE I hold {prop}.',opening:'FIXTURE opening. {request}',response:'FIXTURE response. {counter}',challenge:'FIXTURE challenge.',closing:'FIXTURE closing.'};input.bindings[0].transfer=before;
 const writer=f.writer(input);writer.bindings=[{key:'S131',compatible:false,assessment:'FIXTURE demonstrated transfer wording mismatch.'}];const review=f.review(c.reviewerInput(input,writer));review.bindings=structuredClone(writer.bindings);
 const after={...before,response:'FIXTURE amended response. {counter}'},spec={schema:3,key:'S131',selectedIds:before.seedIds,beforeTransfer:before,beforeTransferHash:c.hash(before),afterTransfer:after,afterTransferHash:c.hash(after),authorAssessment:'FIXTURE ONLY A1 and A3 source correspondence; no production rating or editorial claim.'};
 const blind=t.blind(input,writer,spec);assert.deepEqual(blind.records,[]);assert.ok(!JSON.stringify(blind).includes('weightedTotal'));const binding={records:[],bindings:[{key:'S131',compatible:true,assessment:'FIXTURE ONLY verified body correspondence, no individual pair approval.'}]};
 const effective=t.derive(input,writer,review,spec,binding);assert.deepEqual(effective.writer.records,writer.records);assert.deepEqual(effective.review.records,review.records);assert.deepEqual(effective.input,input);
 for(const field of ['cardId','fingerprint','reviewStatus','seedIds','seedBindingHashes']){const bad=structuredClone(spec);bad.afterTransfer[field]='tampered';bad.afterTransferHash=c.hash(bad.afterTransfer);assert.throws(()=>t.scope(bad));}
 const slot=structuredClone(spec);slot.afterTransfer.response='FIXTURE lost counter slot';slot.afterTransferHash=c.hash(slot.afterTransfer);assert.throws(()=>t.scope(slot),/slots/);
 assert.throws(()=>t.scope({...spec,key:'S06'}),/scope/);assert.throws(()=>t.derive(input,writer,review,spec,{records:[],bindings:[{...binding.bindings[0],compatible:false}]}),/rejected/);
 const root=temp(),expected=t.expectedApplied(spec,writer);c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S131:{...before,seedBindingHashes:expected.seedBindingHashes}}});c.save(path.join(root,'examples/authoring/single-scenes.json'),{records:{S131:{examples:writer.records.map(w=>({id:w.exampleId,beats:w.beats}))}}});t.applySource(root,spec,writer);t.assertApplied(root,spec);
 const drift=c.read(path.join(root,'examples/authoring/stance-transfers.json'));drift.records.S131.closing='Unreviewed change';c.save(path.join(root,'examples/authoring/stance-transfers.json'),drift);assert.throws(()=>t.assertApplied(root,spec),/differs/);
});


test('S139 demonstrated transfer amendments freeze scene reviews and reject metadata, slot and source drift',()=>{
 const t=require('../tools/local-audit/transfer-amendment.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S139'));
 const before={cardId:'S139',fingerprint:'FIXTURE fingerprint',seedIds:['S139-single-a','S139-single-b'],seedBindingHashes:input.records.map(r=>c.hash(r.before.beats)),reviewStatus:'compiled-pair-draft',action:'FIXTURE I hold {prop}.',opening:'FIXTURE opening. {request}',response:'FIXTURE response. {counter}',challenge:'FIXTURE challenge.',closing:'FIXTURE closing.'};input.bindings[0].transfer=before;
 const writer=f.writer(input);writer.bindings=[{key:'S139',compatible:false,assessment:'FIXTURE demonstrated transfer wording mismatch.'}];const review=f.review(c.reviewerInput(input,writer));review.bindings=structuredClone(writer.bindings);
 const after={...before,response:'FIXTURE amended response. {counter}'},spec={schema:3,key:'S139',selectedIds:before.seedIds,beforeTransfer:before,beforeTransferHash:c.hash(before),afterTransfer:after,afterTransferHash:c.hash(after),authorAssessment:'FIXTURE ONLY A1 and A3 source correspondence; no production rating or editorial claim.'};
 const blind=t.blind(input,writer,spec);assert.deepEqual(blind.records,[]);assert.ok(!JSON.stringify(blind).includes('weightedTotal'));const binding={records:[],bindings:[{key:'S139',compatible:true,assessment:'FIXTURE ONLY verified body correspondence, no individual pair approval.'}]};
 const effective=t.derive(input,writer,review,spec,binding);assert.deepEqual(effective.writer.records,writer.records);assert.deepEqual(effective.review.records,review.records);assert.deepEqual(effective.input,input);
 for(const field of ['cardId','fingerprint','reviewStatus','seedIds','seedBindingHashes']){const bad=structuredClone(spec);bad.afterTransfer[field]='tampered';bad.afterTransferHash=c.hash(bad.afterTransfer);assert.throws(()=>t.scope(bad));}
 const slot=structuredClone(spec);slot.afterTransfer.response='FIXTURE lost counter slot';slot.afterTransferHash=c.hash(slot.afterTransfer);assert.throws(()=>t.scope(slot),/slots/);
 assert.throws(()=>t.scope({...spec,key:'S06'}),/scope/);assert.throws(()=>t.derive(input,writer,review,spec,{records:[],bindings:[{...binding.bindings[0],compatible:false}]}),/rejected/);
 const root=temp(),expected=t.expectedApplied(spec,writer);c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S139:{...before,seedBindingHashes:expected.seedBindingHashes}}});c.save(path.join(root,'examples/authoring/single-scenes.json'),{records:{S139:{examples:writer.records.map(w=>({id:w.exampleId,beats:w.beats}))}}});t.applySource(root,spec,writer);t.assertApplied(root,spec);
 const drift=c.read(path.join(root,'examples/authoring/stance-transfers.json'));drift.records.S139.closing='Unreviewed change';c.save(path.join(root,'examples/authoring/stance-transfers.json'),drift);assert.throws(()=>t.assertApplied(root,spec),/differs/);
});


test('S152 demonstrated transfer amendments freeze scene reviews and reject metadata, slot and source drift',()=>{
 const t=require('../tools/local-audit/transfer-amendment.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S152'));
 const before={cardId:'S152',fingerprint:'FIXTURE fingerprint',seedIds:['S152-single-a','S152-single-b'],seedBindingHashes:input.records.map(r=>c.hash(r.before.beats)),reviewStatus:'compiled-pair-draft',action:'FIXTURE I hold {prop}.',opening:'FIXTURE opening. {request}',response:'FIXTURE response. {counter}',challenge:'FIXTURE challenge.',closing:'FIXTURE closing.'};input.bindings[0].transfer=before;
 const writer=f.writer(input);writer.bindings=[{key:'S152',compatible:false,assessment:'FIXTURE demonstrated transfer wording mismatch.'}];const review=f.review(c.reviewerInput(input,writer));review.bindings=structuredClone(writer.bindings);
 const after={...before,response:'FIXTURE amended response. {counter}'},spec={schema:3,key:'S152',selectedIds:before.seedIds,beforeTransfer:before,beforeTransferHash:c.hash(before),afterTransfer:after,afterTransferHash:c.hash(after),authorAssessment:'FIXTURE ONLY A1 and A3 source correspondence; no production rating or editorial claim.'};
 const blind=t.blind(input,writer,spec);assert.deepEqual(blind.records,[]);assert.ok(!JSON.stringify(blind).includes('weightedTotal'));const binding={records:[],bindings:[{key:'S152',compatible:true,assessment:'FIXTURE ONLY verified body correspondence, no individual pair approval.'}]};
 const effective=t.derive(input,writer,review,spec,binding);assert.deepEqual(effective.writer.records,writer.records);assert.deepEqual(effective.review.records,review.records);assert.deepEqual(effective.input,input);
 for(const field of ['cardId','fingerprint','reviewStatus','seedIds','seedBindingHashes']){const bad=structuredClone(spec);bad.afterTransfer[field]='tampered';bad.afterTransferHash=c.hash(bad.afterTransfer);assert.throws(()=>t.scope(bad));}
 const slot=structuredClone(spec);slot.afterTransfer.response='FIXTURE lost counter slot';slot.afterTransferHash=c.hash(slot.afterTransfer);assert.throws(()=>t.scope(slot),/slots/);
 assert.throws(()=>t.scope({...spec,key:'S06'}),/scope/);assert.throws(()=>t.derive(input,writer,review,spec,{records:[],bindings:[{...binding.bindings[0],compatible:false}]}),/rejected/);
 const root=temp(),expected=t.expectedApplied(spec,writer);c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S152:{...before,seedBindingHashes:expected.seedBindingHashes}}});c.save(path.join(root,'examples/authoring/single-scenes.json'),{records:{S152:{examples:writer.records.map(w=>({id:w.exampleId,beats:w.beats}))}}});t.applySource(root,spec,writer);t.assertApplied(root,spec);
 const drift=c.read(path.join(root,'examples/authoring/stance-transfers.json'));drift.records.S152.closing='Unreviewed change';c.save(path.join(root,'examples/authoring/stance-transfers.json'),drift);assert.throws(()=>t.assertApplied(root,spec),/differs/);
});

test('observed WebSocket closing-handshake reconnect still requires exact completed output',()=>{
 const output={fixture:'complete'},retry={type:'error',message:'Reconnecting... 2/5 (stream disconnected before completion: WebSocket protocol error: Connection reset without closing handshake)'},message={type:'item.completed',item:{type:'agent_message',text:JSON.stringify(output)}},done={type:'turn.completed'};
 assert.deepEqual(worker.validateEvents([retry,message,done],output),[retry]);
 for(const events of [[retry,message],[retry,message,done,retry],[retry,{type:'turn.failed'},message,done],[{type:'error',message:'Reconnecting... 2/5 (permission denied)'},message,done],[{type:'error',message:'Reconnecting... 2/5 (stream disconnected before completion: WebSocket protocol error: UNKNOWN)'},message,done],[retry,{type:'item.completed',item:{type:'command_execution'}},message,done]])assert.throws(()=>worker.validateEvents(events,output));
 assert.throws(()=>worker.validateEvents([retry,message,done],{fixture:'mismatch'}));
});

test('proved recovered writer resolves only its classifier failure without resetting limits or editorial rounds',()=>{
 const tr=require('../tools/local-audit/transport-recovery.cjs'),policy=require('../tools/local-audit/editorial-policy.cjs'),base=temp(),source=path.join(base,'attempt-01'),dest=path.join(base,'attempt-03'),input=f.input(),writer=f.writer(input);fs.mkdirSync(source);const schema=path.join(source,'schema.json');c.save(schema,worker.schemas.writer);c.save(path.join(source,'writer.json'),writer);c.save(path.join(source,'writer.input.json'),input);c.save(path.join(source,'writer.process.json'),{code:0,timedOut:false,elapsedMs:1,command:['fixture','read-only','--ephemeral','--output-schema',schema]});fs.writeFileSync(path.join(source,'writer.prompt.txt'),worker.prompt('writer',input,'FIXTURE rubric','FIXTURE context',null));const retry={type:'error',message:'Reconnecting... 2/5 (stream disconnected before completion: WebSocket protocol error: Connection reset without closing handshake)'};const events=out=>[{type:'item.completed',item:{type:'agent_message',text:JSON.stringify(out)}},{type:'turn.completed'}];fs.writeFileSync(path.join(source,'writer.stdout.log'),[retry,...events(writer)].map(JSON.stringify).join('\n'));tr.recoverCompletedWriter(source,dest,input);
 const review=f.review(c.reviewerInput(input,writer));review.records[0].accept=false;c.save(path.join(dest,'reviewer.json'),review);c.save(path.join(dest,'reviewer.proof.json'),{freshInvocation:true,toolsUsed:false,outputHash:c.hash(review)});c.save(path.join(dest,'reviewer.process.json'),{code:0,timedOut:false,command:['fixture','read-only','--ephemeral']});fs.writeFileSync(path.join(dest,'reviewer.stdout.log'),events(review).map(JSON.stringify).join('\n'));
 const failed={id:'attempt-01',status:'failed',stage:'writer',error:'Worker reported failure'},b={correctionPolicy:{maxCorrections:2,authorizationHash:'fixture'},attempts:[failed,{id:'attempt-02',status:'failed',stage:'writer',error:'timedOut=true'},{id:'attempt-03',status:'rejected',writerReusedFrom:'attempt-01',writerReference:path.join(dest,'writer.json'),reviewReference:path.join(dest,'reviewer.json'),critique:{review}}]},q={limits:{maxAttempts:2}};assert.equal(policy.mayStart(q,b),false);const history=structuredClone(b.attempts),link={failedAttempt:'attempt-01',failedAttemptHash:c.hash(failed),recoveredAttempt:'attempt-03',writerProofHash:c.hash(c.read(path.join(dest,'writer.proof.json')))};b.resolvedTransportFailures=[link];assert.equal(policy.mayStart(q,b),true);assert.equal(policy.technicalLimit(q,b),2);assert.deepEqual(b.attempts,history);assert.deepEqual([...tr.resolvedFailures(b)],['attempt-01']);
 b.resolvedTransportFailures.push(link);assert.throws(()=>policy.mayStart(q,b),/Duplicate/);b.resolvedTransportFailures.pop();b.attempts[0].error='permission denied';assert.throws(()=>policy.mayStart(q,b));b.attempts[0]={...history[0]};
 b.attempts.push({status:'rejected',critique:{review}},{status:'rejected',critique:{review}});assert.equal(policy.mayStart(q,b),false);b.attempts.splice(3);c.save(path.join(source,'writer.process.json'),{code:1,timedOut:false});assert.throws(()=>policy.mayStart(q,b));
});
test('S130 demonstrated transfer amendments freeze scene reviews and reject metadata, slot and source drift',()=>{
 const t=require('../tools/local-audit/transfer-amendment.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S130'));
 const before={cardId:'S130',fingerprint:'FIXTURE fingerprint',seedIds:['S130-single-a','S130-single-b'],seedBindingHashes:input.records.map(r=>c.hash(r.before.beats)),reviewStatus:'compiled-pair-draft',action:'FIXTURE I hold {prop}.',opening:'FIXTURE opening. {request}',response:'FIXTURE response. {counter}',challenge:'FIXTURE challenge.',closing:'FIXTURE closing.'};input.bindings[0].transfer=before;
 const writer=f.writer(input);writer.bindings=[{key:'S130',compatible:false,assessment:'FIXTURE demonstrated transfer wording mismatch.'}];const review=f.review(c.reviewerInput(input,writer));review.bindings=structuredClone(writer.bindings);
 const after={...before,response:'FIXTURE amended response. {counter}'},spec={schema:3,key:'S130',selectedIds:before.seedIds,beforeTransfer:before,beforeTransferHash:c.hash(before),afterTransfer:after,afterTransferHash:c.hash(after),authorAssessment:'FIXTURE ONLY A1 and A3 source correspondence; no production rating or editorial claim.'};
 const blind=t.blind(input,writer,spec);assert.deepEqual(blind.records,[]);assert.ok(!JSON.stringify(blind).includes('weightedTotal'));const binding={records:[],bindings:[{key:'S130',compatible:true,assessment:'FIXTURE ONLY verified body correspondence, no individual pair approval.'}]};
 const effective=t.derive(input,writer,review,spec,binding);assert.deepEqual(effective.writer.records,writer.records);assert.deepEqual(effective.review.records,review.records);assert.deepEqual(effective.input,input);
 for(const field of ['cardId','fingerprint','reviewStatus','seedIds','seedBindingHashes']){const bad=structuredClone(spec);bad.afterTransfer[field]='tampered';bad.afterTransferHash=c.hash(bad.afterTransfer);assert.throws(()=>t.scope(bad));}
 const slot=structuredClone(spec);slot.afterTransfer.response='FIXTURE lost counter slot';slot.afterTransferHash=c.hash(slot.afterTransfer);assert.throws(()=>t.scope(slot),/slots/);
 assert.throws(()=>t.scope({...spec,key:'S06'}),/scope/);assert.throws(()=>t.derive(input,writer,review,spec,{records:[],bindings:[{...binding.bindings[0],compatible:false}]}),/rejected/);
 const root=temp(),expected=t.expectedApplied(spec,writer);c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S130:{...before,seedBindingHashes:expected.seedBindingHashes}}});c.save(path.join(root,'examples/authoring/single-scenes.json'),{records:{S130:{examples:writer.records.map(w=>({id:w.exampleId,beats:w.beats}))}}});t.applySource(root,spec,writer);t.assertApplied(root,spec);
 const drift=c.read(path.join(root,'examples/authoring/stance-transfers.json'));drift.records.S130.closing='Unreviewed change';c.save(path.join(root,'examples/authoring/stance-transfers.json'),drift);assert.throws(()=>t.assertApplied(root,spec),/differs/);
});


test('S157 demonstrated transfer amendments freeze scene reviews and reject metadata, slot and source drift',()=>{
 const t=require('../tools/local-audit/transfer-amendment.cjs'),input=JSON.parse(JSON.stringify(f.input()).replaceAll('S01','S157'));
 const before={cardId:'S157',fingerprint:'FIXTURE fingerprint',seedIds:['S157-single-a','S157-single-b'],seedBindingHashes:input.records.map(r=>c.hash(r.before.beats)),reviewStatus:'compiled-pair-draft',action:'FIXTURE I hold {prop}.',opening:'FIXTURE opening. {request}',response:'FIXTURE response. {counter}',challenge:'FIXTURE challenge.',closing:'FIXTURE closing.'};input.bindings[0].transfer=before;
 const writer=f.writer(input);writer.bindings=[{key:'S157',compatible:false,assessment:'FIXTURE demonstrated transfer wording mismatch.'}];const review=f.review(c.reviewerInput(input,writer));review.bindings=structuredClone(writer.bindings);
 const after={...before,response:'FIXTURE amended response. {counter}'},spec={schema:3,key:'S157',selectedIds:before.seedIds,beforeTransfer:before,beforeTransferHash:c.hash(before),afterTransfer:after,afterTransferHash:c.hash(after),authorAssessment:'FIXTURE ONLY A1 and A3 source correspondence; no production rating or editorial claim.'};
 const blind=t.blind(input,writer,spec);assert.deepEqual(blind.records,[]);assert.ok(!JSON.stringify(blind).includes('weightedTotal'));const binding={records:[],bindings:[{key:'S157',compatible:true,assessment:'FIXTURE ONLY verified body correspondence, no individual pair approval.'}]};
 const effective=t.derive(input,writer,review,spec,binding);assert.deepEqual(effective.writer.records,writer.records);assert.deepEqual(effective.review.records,review.records);assert.deepEqual(effective.input,input);
 for(const field of ['cardId','fingerprint','reviewStatus','seedIds','seedBindingHashes']){const bad=structuredClone(spec);bad.afterTransfer[field]='tampered';bad.afterTransferHash=c.hash(bad.afterTransfer);assert.throws(()=>t.scope(bad));}
 const slot=structuredClone(spec);slot.afterTransfer.response='FIXTURE lost counter slot';slot.afterTransferHash=c.hash(slot.afterTransfer);assert.throws(()=>t.scope(slot),/slots/);
 assert.throws(()=>t.scope({...spec,key:'S06'}),/scope/);assert.throws(()=>t.derive(input,writer,review,spec,{records:[],bindings:[{...binding.bindings[0],compatible:false}]}),/rejected/);
 const root=temp(),expected=t.expectedApplied(spec,writer);c.save(path.join(root,'examples/authoring/stance-transfers.json'),{records:{S157:{...before,seedBindingHashes:expected.seedBindingHashes}}});c.save(path.join(root,'examples/authoring/single-scenes.json'),{records:{S157:{examples:writer.records.map(w=>({id:w.exampleId,beats:w.beats}))}}});t.applySource(root,spec,writer);t.assertApplied(root,spec);
 const drift=c.read(path.join(root,'examples/authoring/stance-transfers.json'));drift.records.S157.closing='Unreviewed change';c.save(path.join(root,'examples/authoring/stance-transfers.json'),drift);assert.throws(()=>t.assertApplied(root,spec),/differs/);
});


test('D119 and D126 description scopes reject unrelated pairs, dialogue mutation and stale provenance',()=>{
 const pa=require('../tools/local-audit/provenance-amendment.cjs');
 for(const [key,pair] of [['D119','S118+D119'],['D126','S144+D126']]){
  const before={id:pair+'-a',beats:f.input().records[0].before.beats,seedRefs:[pair.split('+')[0]+'-single-a',key+'-single-a'],seedUse:'FIXTURE historical seed contribution only.',editorialStatus:'pending'},after={...before,seedUse:'FIXTURE historical contribution and current retained detail; pair semantic review remains pending.'};
  const change={exampleId:before.id,beforeSeedUse:before.seedUse,afterSeedUse:after.seedUse,beforeSeedRefs:before.seedRefs,afterSeedRefs:after.seedRefs,beforeRecordHash:c.hash(before),afterRecordHash:c.hash(after),reason:'FIXTURE ONLY explicit historical/current seed distinction.'},spec={schema:2,selectedIds:[key+'-single-a',key+'-single-b'],repairs:[{key,changes:[change],authorAssessment:'FIXTURE ONLY A1 concrete contribution; no production approval.'}]};
  pa.scope(spec);const applied=pa.changedPairs([before],[change]);assert.deepEqual(applied[0].beats,before.beats);assert.equal(applied[0].editorialStatus,'pending');
  const wrong=structuredClone(spec);wrong.repairs[0].changes[0].exampleId='S06+D49-b';assert.throws(()=>pa.scope(wrong),/Unrelated pair/);
  const stale={...change,beforeRecordHash:'stale'};assert.throws(()=>pa.changedPairs([before],[stale]),/conflict/);
  const changedDialogue={...after,beats:[...after.beats].reverse()};assert.throws(()=>pa.changedPairs([before],[{...change,afterRecordHash:c.hash(changedDialogue)}]),/conflict/);
  assert.throws(()=>pa.changedPairs([before],[{...change,afterSeedRefs:['S06-single-a',key+'-single-a']}]),/Cross-card/);
 }
});


test('successive provenance amendments require a unique complete hash chain',()=>{const {followChain}=require('../tools/local-audit/provenance-amendment.cjs'),edges=[{beforeRecordHash:'old',afterRecordHash:'middle'},{beforeRecordHash:'middle',afterRecordHash:'current'}];assert.equal(followChain('old','current',edges),'current');assert.throws(()=>followChain('old','unrecorded',edges),/Missing/);assert.throws(()=>followChain('old','current',[...edges,{beforeRecordHash:'old',afterRecordHash:'fork'}]),/ambiguous/);assert.throws(()=>followChain('old','current',[edges[0],{beforeRecordHash:'middle',afterRecordHash:'old'}]),/cycle/);});
