'use strict';
// Versioned editorial evidence, not a numerical proxy for comprehension.
const assert=require('node:assert/strict');
const version='coach-2.0',gateIds=['G1','G2','G3','G4','G5','G6','format'],links=['A1-B2','B2-A3','A3-B4','B4-A5'];
const str={type:'string'},obj=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const finding=obj({decision:{type:'string',enum:['PASS','FAIL','UNCLEAR']},evidence:str});
const schema=obj({rubricVersion:{type:'string',const:version},dialogueHash:str,inspectionMode:{type:'string',const:'internal-dialogue-first'},situation:str,stated:str,inferred:str,missing:str,firstDefect:str,transitions:obj(Object.fromEntries(links.map(k=>[k,finding]))),mechanism:str,sceneOutline:str,mandatoryGates:obj(Object.fromEntries(gateIds.map(k=>[k,finding]))),humanReviewed:{type:'boolean',const:false},liveTested:{type:'boolean',const:false}});
function active(input){return input?.rubric?.version===version;}
function assertLegacyExecution(state){assert.notEqual(state.requiredRubricVersion,version,'coach-2.0 campaign: legacy resume/integrate-accepted cannot adopt coach-1.0 acceptances; finish versioned recovery and integration');}
function pass(e){return gateIds.every(g=>e.mandatoryGates[g].decision==='PASS')&&links.every(k=>e.transitions[k].decision==='PASS');}
function validate(e,beats){const c=require('./core.cjs');assert.ok(e,'coach-2.0 evidence required');assert.equal(e.rubricVersion,version);assert.equal(e.dialogueHash,c.hash(beats),'coach-2.0 dialogue hash mismatch');assert.equal(e.inspectionMode,'internal-dialogue-first','Cards present: do not claim blindness');assert.equal(e.humanReviewed,false);assert.equal(e.liveTested,false);for(const key of ['situation','stated','inferred','missing','firstDefect','mechanism','sceneOutline']){assert.ok(typeof e[key]==='string'&&e[key].trim().length>=12,'Missing coach-2.0 '+key);}for(const [map,keys]of [[e.mandatoryGates,gateIds],[e.transitions,links]]){assert.deepEqual(Object.keys(map).sort(),keys.slice().sort());for(const key of keys){assert.ok(['PASS','FAIL','UNCLEAR'].includes(map[key].decision));c.evidence(map[key].evidence,key);assert.match(map[key].evidence,/\b[AB][1-5]\b/,'Turn evidence required: '+key);}}if(e.mandatoryGates.G3.decision==='PASS')assert.ok(links.every(k=>e.transitions[k].decision==='PASS'),'G3 cannot pass a failed/unclear transition');return e;}
function extendSchema(base){const s=structuredClone(base),record=s.properties.records.items;record.properties.coach2=schema;record.required.push('coach2');return s;}
const instructions=`PRODUCTION STANDARD coach-2.0. Historical coach-1.0 acceptance is not coach-2.0 acceptance. Read the dialogue first and record what the spoken words establish before interpreting the card. Exact cards are already in this invocation: label internal-dialogue-first, never blind or human review. Do not invent a charitable backstory; harmless unspecified names/history are not defects. Fill coach2 for ORIGINAL dialogue in writer output and CANDIDATE dialogue in reviewer output. Copy the supplied dialogue hash for the text being assessed. Give concise actual turn evidence, not generic claims.
G1: legible immediate situation, wants/stakes; separate stated, ordinary inferred, and missing essentials. Identify first material defect or explicitly none.
G2: coherent facts, ownership, timing, language, knowledge; recognizable misunderstanding/revelation is allowed, unstated intervening events are not.
G3: assess all A1-B2, B2-A3, A3-B4, B4-A5 links. Vocabulary repetition alone is insufficient. Purposeful avoidance must read as behavior.
G4: B is a plausible participant with an intelligible practical/emotional position, not a contrived punchline cue. B can help, concede or solve.
G5: exact card changes A's choices. For pairs Stance changes HOW A pursues Drive and B responds to the merged behavior; neither card may be decorative.
G6: ending develops the same behavior using B4. Investigate if A5 would work after unrelated B4; more obstacles are not required for heightening.
format: five spoken ABABA turns, existing word/schema limit, no narration/coaching/truncation.
Every mandatory gate and transition is PASS, FAIL or UNCLEAR with evidence; UNCLEAR cannot be accepted. All gates pass AND total >=85 AND fidelity/response >=4 AND others >=3; preserve the six weights 30/20/15/15/10/10. A 5 is not merely presence. Totals are derived in code. Retain good originals; no rewrite quota. Review both alternatives for different tactics, relationships or pressure. Scene outline identifies roles, task, A want, B want, stakes, exact-card tactic and B's contribution; it is private planning evidence, not a substitute for missing spoken facts. Humour must come from sincere priorities and responsive choices, not stock hierarchy or unrelated slogans. Record actual weaknesses and reservations. Writer corrections target only rejected/materially changed scenes; preserve all accepted records and prior original assessments exactly. No coach-1.0 failure or exhausted allowance is erased by this separately versioned cycle.`;
module.exports={version,gateIds,links,schema,active,pass,validate,extendSchema,instructions,assertLegacyExecution};
