'use strict';
// Local orchestration only. This module never assigns editorial scores.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {rubric,hash,validPass,accepted}=require('../coach-review-core.cjs');
const gates=['fiveSpokenTurns','aHoldsRequestedCard','b2CausesA3','b4CausesA5','noSeparateNarration','noUnrelatedPunchline','noRealPartnerInstruction','noForcedEnding'];
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function save(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});const tmp=p+'.'+crypto.randomUUID()+'.tmp';fs.writeFileSync(tmp,JSON.stringify(v,null,2)+'\n',{flag:'wx'});for(let n=0;;n++){try{fs.renameSync(tmp,p);break;}catch(e){if(!['EPERM','EACCES','EBUSY'].includes(e.code)||n>=19)throw e;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,100);}}}
function evidence(v,label){assert.ok(typeof v==='string'&&v.trim().length>=20,'Missing evidence: '+label);}
function validatePass(pass,label){
 for(const criterion of rubric.criteria){const rating=pass?.ratings?.[criterion.id];assert.ok(rating&&Number.isInteger(rating.score)&&rating.score>=0&&rating.score<=5,label+': invalid score for '+criterion.id);evidence(rating.evidence,label+' '+criterion.id);assert.match(rating.evidence,/\b[AB][1-5]\b/,label+': cite numbered turns for '+criterion.id);}
 const expected=require('../coach-review-core.cjs').total(pass);assert.ok(validPass(pass),label+': weightedTotal expected '+expected+', received '+pass.weightedTotal);
}
function exactIds(rows,ids){assert.ok(Array.isArray(rows));assert.deepEqual(rows.map(r=>r.exampleId).sort(),[...ids].sort(),'Missing, duplicate or unexpected scene IDs');}
function dialogue(beats){assert.ok(Array.isArray(beats));assert.deepEqual(beats.map(b=>b.speaker),['A','B','A','B','A']);for(const b of beats){assert.deepEqual(Object.keys(b).sort(),['speaker','text']);assert.ok(typeof b.text==='string'&&b.text.trim().length>2);assert.doesNotMatch(b.text,/^\s*[\[\]*]|[<>{}]|\b(?:your stance|your drive|the card holder|one concrete choice|then heighten|as an ai)\b/i);}assert.ok(beats.map(b=>b.text).join(' ').trim().split(/\s+/).length<=75,'Single exceeds existing 75-word gate');}
function ledger(root){const rows=[];for(const d of fs.readdirSync(path.join(root,'editorial'),{withFileTypes:true})){if(!d.isDirectory())continue;for(const f of fs.readdirSync(path.join(root,'editorial',d.name))){if(!f.endsWith('-review.json'))continue;const p='editorial/'+d.name+'/'+f,v=read(path.join(root,p));if(v.rubricVersion===rubric.version&&Array.isArray(v.records))for(const r of v.records)rows.push({...r,reviewReference:p});}}return rows;}
function discover(root){
 const single=read(path.join(root,'examples/authoring/single-scenes.json')).records,pairFile=read(path.join(root,'examples/authoring/pair-scenes.json')),pairs=pairFile.records||pairFile;
 const scenes=new Map([...Object.values(single).flatMap(s=>s.examples),...Object.values(pairs).flat()].map(s=>[s.id,s]));
 const reviews=ledger(root),done=new Map();
 for(const r of reviews){assert.equal(r.status,'internal-second-pass','Incomplete record in completed ledger');assert.ok(!done.has(r.exampleId),'Duplicate completed review');assert.ok(validPass(r.firstPass)&&accepted(r.secondPass),'Invalid completed scores');assert.ok(r.hardGates&&Object.keys(r.hardGates).length&&Object.values(r.hardGates).every(v=>v===true));assert.equal(hash(r.before.beats),r.beforeBeatsSha256);assert.equal(hash(r.after.beats),r.afterBeatsSha256);assert.equal(hash(scenes.get(r.exampleId)?.beats),r.afterBeatsSha256,'Completed source drift: '+r.exampleId);done.set(r.exampleId,r);}
 const singlesReviewed=reviews.filter(r=>r.kind==='single').length,pairsReviewed=reviews.filter(r=>r.kind==='combination').length;
 const manifest=read(path.join(root,'examples/manifest.json'));
 const keys=Object.keys(single).sort((a,b)=>(a[0]===b[0]?Number(a.slice(1))-Number(b.slice(1)):a.startsWith('S')?-1:1));
 return {single,pairs,done,progress:{singlesReviewed,singlesTotal:Object.values(single).flatMap(s=>s.examples).length,pairsReviewed,pairsTotal:manifest.counts.pairExamples},pendingKeys:keys.filter(k=>single[k].examples.some(s=>!done.has(s.id)))};
}
function plan(root,options={}){
 for(const name of ['maxBatches','maxMinutes','maxAttempts'])assert.notEqual(typeof options[name],'boolean','A numeric value is required for '+name);
 const maxBatches=Number(options.maxBatches??5),maxMinutes=Number(options.maxMinutes??240),maxAttempts=Number(options.maxAttempts??2);
 assert.ok(Number.isInteger(maxBatches)&&maxBatches>=1&&maxBatches<=5,'This runner is capped at five batches per queue');assert.ok(Number.isFinite(maxMinutes)&&maxMinutes>0&&maxMinutes<=1440);assert.ok(Number.isInteger(maxAttempts)&&maxAttempts>=1&&maxAttempts<=3);
 const d=discover(root),id=options.id||'singles-'+new Date().toISOString().replace(/[^0-9]/g,'');assert.match(id,/^[a-zA-Z0-9_-]{1,70}$/);
 const batches=[];for(let i=0;i<d.pendingKeys.length&&batches.length<maxBatches;i+=10){const keys=d.pendingKeys.slice(i,i+10);batches.push({id:'batch-'+String(batches.length+1).padStart(3,'0'),keys,status:'pending',attempts:[],reviews:[],validation:[],scenes:keys.flatMap(k=>d.single[k].examples.map(s=>({exampleId:s.id,key:k,sourceHash:hash(s.beats),sourceRecordHash:hash(s),status:d.done.has(s.id)?'reference':'pending',reviewReference:d.done.get(s.id)?.reviewReference||null,attempts:0})))});}
 return {schema:1,type:'local-coach-queue',id,root:path.resolve(root),createdAt:new Date().toISOString(),rubricVersion:rubric.version,rubricHash:hash(rubric),publicVersion:read(path.join(root,'package.json')).version,startingProgress:d.progress,limits:{maxBatches,maxMinutes,maxAttempts},elapsedMs:0,status:'ready',stopReason:null,batches};
}
function writerInput(root,batch){const d=discover(root),transfers=read(path.join(root,'examples/authoring/stance-transfers.json')).records;return {rubric,records:batch.scenes.map(s=>({exampleId:s.exampleId,key:s.key,reference:s.status==='reference',before:d.single[s.key].examples.find(e=>e.id===s.exampleId),beforeHash:s.sourceHash,card:Object.fromEntries(['id','type','title','instruction','contentVersion'].map(k=>[k,k==='id'?s.key:k==='type'?(s.key.startsWith('S')?'stance':'drive'):d.single[s.key][k]]))})),bindings:batch.keys.map(key=>({key,transfer:transfers[key]||null,bespokePairs:Object.values(d.pairs).flat().filter(p=>p.seedRefs.some(id=>id.startsWith(key+'-single-'))),supportingSeeds:[...new Set(Object.values(d.pairs).flat().filter(p=>p.seedRefs.some(id=>id.startsWith(key+'-single-'))).flatMap(p=>p.seedRefs))].map(id=>{const seedKey=id.split('-single-')[0],card=d.single[seedKey];assert.ok(card,'Missing referenced seed card '+id);const scene=card.examples.find(s=>s.id===id);assert.ok(scene,'Missing referenced seed '+id);return {card:{id:seedKey,title:card.title,instruction:card.instruction,contentVersion:card.contentVersion},scene,sourceHash:hash(scene)};})}))};}
function validateWriter(input,output){
 const v2=require('./coach2.cjs');if(v2.active(input))for(const r of output.records){const original=input.records.find(x=>x.exampleId===r.exampleId);assert.ok(original);v2.validate(r.coach2,original.before.beats);if(r.decision==='retained')assert.ok(v2.pass(r.coach2),'coach-2.0 weak original cannot be retained');}

 exactIds(output.records,input.records.filter(r=>!r.reference).map(r=>r.exampleId));assert.deepEqual(output.bindings.map(b=>b.key).sort(),input.bindings.map(b=>b.key).sort());
 for(const b of output.bindings){evidence(b.assessment,'transfer and seed inputs '+b.key);assert.equal(typeof b.compatible,'boolean');}
 for(const r of output.records){const original=input.records.find(o=>o.exampleId===r.exampleId);assert.equal(r.beforeHash,original.beforeHash);validatePass(r.firstPass,r.exampleId+' firstPass');for(const k of ['mechanism','confusableConcept','distinguishingEvidence','alternativeComparison','reason','reservation'])evidence(r[k],r.exampleId+' '+k+' (minimum 20 characters)');dialogue(r.beats);assert.ok(['retained','revised'].includes(r.decision));assert.equal(r.decision==='retained',hash(r.beats)===original.beforeHash);if(r.decision==='retained')assert.ok(accepted(r.firstPass),'Weak original cannot be retained');}
 return output;
}
function reviewerInput(input,writer){return {rubric:input.rubric||rubric,records:input.records.map(r=>({exampleId:r.exampleId,card:r.card,reference:r.reference,beats:writer.records.find(w=>w.exampleId===r.exampleId)?.beats||r.before.beats})),bindings:input.bindings};}
function validateReview(input,output){const v2=require('./coach2.cjs');if(v2.active(input))for(const r of output.records){const candidate=input.records.find(x=>x.exampleId===r.exampleId);assert.ok(candidate);v2.validate(r.coach2,candidate.beats);dialogue(candidate.beats);if(r.accept)assert.ok(v2.pass(r.coach2),'coach-2.0 mandatory gates must all pass');}
exactIds(output.records,input.records.filter(r=>!r.reference).map(r=>r.exampleId));assert.deepEqual(output.bindings.map(b=>b.key).sort(),input.bindings.map(b=>b.key).sort());for(const b of output.bindings){evidence(b.assessment,'binding review');assert.equal(typeof b.compatible,'boolean');}
 for(const r of output.records){const candidate=input.records.find(o=>o.exampleId===r.exampleId);assert.equal(r.candidateHash,hash(candidate.beats),'Reviewer rated different dialogue');validatePass(r.secondPass,r.exampleId+' secondPass');assert.deepEqual(Object.keys(r.hardGates).sort(),[...gates].sort());for(const g of gates)assert.equal(typeof r.hardGates[g],'boolean');for(const k of ['b2CausesA3','b4CausesA5','cardContribution','sameGameHeightened'])evidence(r.hardGateEvidence[k],k);evidence(r.reservation,'second-pass reservation');evidence(r.alternativeComparison,'second-pass alternative comparison');assert.equal(typeof r.accept,'boolean');if(r.accept)assert.ok(accepted(r.secondPass)&&gates.every(g=>r.hardGates[g]),'Acceptance must follow unchanged rubric and all hard gates');}
 return output;
}
function allAccepted(writer,review){return review.records.every(r=>r.accept)&&writer.bindings.every(b=>b.compatible)&&review.bindings.every(b=>b.compatible);}
const excluded=new Set(['.git','.audit-runs','.checkpoint-work','releases','reports','node_modules','__pycache__','.audit-runner.lock']);
function files(root,relative=''){const out=[];for(const e of fs.readdirSync(path.join(root,relative),{withFileTypes:true})){if(excluded.has(e.name)||e.name.startsWith('.audit-runner.lock')||e.name.endsWith('.audit-tmp')||e.name.endsWith('.pyc'))continue;const rel=path.join(relative,e.name);assert.ok(!e.isSymbolicLink(),'Source snapshot refuses symlinks: '+rel);if(e.isDirectory())out.push(...files(root,rel));else out.push(rel);}return out.sort();}
function fingerprint(root){return Object.fromEntries(files(root).map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]));}
function copySource(root,dest){assert.ok(!fs.existsSync(dest),'Staging directory must be fresh');fs.mkdirSync(dest,{recursive:true});for(const f of files(root)){const p=path.join(dest,f);fs.mkdirSync(path.dirname(p),{recursive:true});fs.copyFileSync(path.join(root,f),p);}fs.mkdirSync(path.join(dest,'reports'),{recursive:true});}
function compareDataset(beforeRoot,afterRoot,directIds,provenanceFolders=[]){const referenceAmendments=require('./provenance-amendment.cjs').referenceAmendments(beforeRoot,afterRoot,directIds,provenanceFolders);const load=root=>{const m=read(path.join(root,'examples/manifest.json'));return new Map(Object.values(m.files).flatMap(f=>Object.values(read(path.join(root,f.plainUrl)).records).flat()).map(r=>[r.id,r]));};const before=load(beforeRoot),after=load(afterRoot),direct=new Set(directIds),changedSeeds=new Set([...direct].filter(id=>hash(before.get(id).beats)!==hash(after.get(id).beats)));assert.equal(before.size,after.size);const out={total:before.size,reviewed:[...direct],directlyRevised:[],retained:[],unchangedDialogue:0,mechanicallyChangedPairDialogue:[],dependentReferences:[],otherRecordChanges:[]};for(const [id,b] of before){const a=after.get(id);assert.ok(a,'Missing stable ID '+id);const changed=hash(a.beats)!==hash(b.beats);if(direct.has(id))out[changed?'directlyRevised':'retained'].push(id);else if(changed){assert.ok(a.seedRefs?.some(s=>changedSeeds.has(s)),'Unrelated dialogue changed '+id);assert.equal(a.editorialStatus,'pair-review-pending');out.mechanicallyChangedPairDialogue.push(id);}if(!changed)out.unchangedDialogue++;if(a.seedRefs?.some(s=>changedSeeds.has(s)))out.dependentReferences.push({exampleId:id,changedSeedRefs:a.seedRefs.filter(s=>changedSeeds.has(s)),dialogueChanged:changed,reviewStatus:a.editorialStatus});if(hash(a)!==hash(b)&&!changed&&!direct.has(id)){require('./provenance-amendment.cjs').assertReferenceChange(b,a,referenceAmendments.get(id));out.otherRecordChanges.push(id);}}return out;}
function summary(q){const scenes=q.batches.flatMap(b=>b.scenes.map(s=>s.status==='failed'&&b.attempts.at(-1)?.status==='failed'?{...s,status:'blocked'}:s));const ids=status=>scenes.filter(s=>s.status===status).map(s=>s.exampleId);return {queue:q.id,status:q.status,stopReason:q.stopReason,completed:ids('retained').length+ids('revised').length,retained:ids('retained'),revised:ids('revised'),failed:ids('failed'),acceptedStaged:ids('accepted-staged'),unresolved:ids('unresolved'),exceptions:q.batches.filter(b=>['exception','partial'].includes(b.status)).map(b=>({batch:b.id,...b.exception,parentStatus:b.status,historicalException:b.exception,acceptedStaged:b.scenes.filter(s=>s.status==='accepted-staged').map(s=>s.exampleId),unresolved:b.scenes.filter(s=>s.status==='unresolved').map(s=>s.exampleId),integratedSceneIds:b.scenes.filter(s=>s.acceptedHash).map(s=>s.exampleId)})),pending:scenes.filter(s=>['pending','active','blocked'].includes(s.status)).map(s=>s.exampleId),blocked:ids('blocked'),diagnostics:q.batches.flatMap(b=>b.attempts.filter(a=>a.error).map(a=>({batch:b.id,attempt:a.id,stage:a.stage||'writer-validation',error:a.error,paths:a.diagnosticPaths||{}}))),references:ids('reference'),elapsedMs:q.elapsedMs,usage:q.batches.flatMap(b=>b.attempts).flatMap(a=>a.usage||[]),batches:q.batches.map(b=>({id:b.id,keys:b.keys,status:b.status,validation:b.validation,reviewReferences:b.reviews}))};}
function attemptLimit(q,b){if(b.correctionPolicy){require('./editorial-policy.cjs').validate(q,b);return require('./editorial-policy.cjs').technicalLimit(q,b)+3;}const base=b.recovery?b.recovery.startIndex+b.recovery.maxAttempts:q.limits.maxAttempts;if(!b.editorialAllowance)return base;const a=b.editorialAllowance;assert.equal(a.startIndex,base,'Separate editorial allowance must follow exhausted recovery');assert.ok(Number.isInteger(a.maxAttempts)&&a.maxAttempts>=1&&a.maxAttempts<=2,'Editorial allowance is capped at two rounds');assert.ok(a.authorizationHash&&a.snapshot&&a.reason?.length>=20,'Explicit editorial authorization evidence required');const prior=b.attempts[a.startIndex-1];assert.equal(prior?.status,'rejected');assert.deepEqual([...a.sceneIds].sort(),prior.critique.review.records.filter(r=>!r.accept).map(r=>r.exampleId).sort(),'Editorial allowance must target exactly the rejected scenes');return base+a.maxAttempts;}
function validateBounds(q){assert.ok(Number.isInteger(q.limits.maxBatches)&&q.limits.maxBatches>=1&&q.limits.maxBatches<=5&&q.batches.length<=q.limits.maxBatches);assert.ok(Number.isInteger(q.limits.maxAttempts)&&q.limits.maxAttempts>=1&&q.limits.maxAttempts<=3);assert.ok(Number.isFinite(q.limits.maxMinutes)&&q.limits.maxMinutes>0&&q.limits.maxMinutes<=1440);const ids=new Set();for(const b of q.batches){require('./editorial-policy.cjs').validate(q,b);if(b.recovery){assert.ok(Number.isInteger(b.recovery.startIndex)&&b.recovery.startIndex>=1);assert.ok(Number.isInteger(b.recovery.maxAttempts)&&b.recovery.maxAttempts>=1&&b.recovery.maxAttempts<=3,'Recovery is capped at three attempts');assert.ok(b.attempts.length<=attemptLimit(q,b),'Recovery attempt budget exceeded');}assert.ok(b.keys.length>=1&&b.keys.length<=10&&b.scenes.length===b.keys.length*2);for(const key of b.keys){assert.match(key,/^[SD]\d{2,3}$/);assert.deepEqual(b.scenes.filter(s=>s.key===key).map(s=>s.exampleId).sort(),[key+'-single-a',key+'-single-b']);}for(const s of b.scenes){assert.ok(!ids.has(s.exampleId),'Repeated queued scene');ids.add(s.exampleId);}}}
function batchReport(records){return '# Applied local two-pass review\n\nModel review, not human approval or live testing.\n\n'+records.map(r=>'## '+r.exampleId+' — '+r.decision+'\n\n'+r.cards[0].instruction+'\n\nMechanism: '+r.mechanismDistinction.mechanism+'\n\nConfusable concept: '+r.mechanismDistinction.confusableConcept+'\n\n'+['before','after'].map(k=>'### '+k+'\n\n'+r[k].beats.map(b=>'**'+b.speaker+':** '+b.text).join('\n\n')).join('\n\n')+'\n\nFirst / second pass: '+r.firstPass.weightedTotal+' / '+r.secondPass.weightedTotal+'\n\n'+rubric.criteria.map(c=>'- '+c.id+': original '+r.firstPass.ratings[c.id].score+' — '+r.firstPass.ratings[c.id].evidence+' Result '+r.secondPass.ratings[c.id].score+' — '+r.secondPass.ratings[c.id].evidence).join('\n')+'\n\nB4 causes A5: '+r.hardGateEvidence.b4CausesA5+'\n\nAlternatives: '+r.alternativeComparison+'\n\nReservation: '+r.remainingConcern).join('\n\n')+'\n';}
module.exports={read,save,sha,hash,rubric,gates,evidence,dialogue,ledger,discover,plan,writerInput,validateWriter,reviewerInput,validateReview,allAccepted,files,fingerprint,copySource,compareDataset,summary,validateBounds,attemptLimit,batchReport};
