'use strict';
const assert=require('node:assert/strict');
// Technical failures and completed editorial rounds have separate allowances.
function enabled(b){return Boolean(b.correctionPolicy);}
function technicalLimit(q,b){const r=b.technicalRecovery;if(!r)return q.limits.maxAttempts;if(r.kind==='interrupted-phase'){assert.equal(r.maxAttempts,1);assert.match(r.authorizationHash,/^[a-f0-9]{64}$/);assert.ok(r.snapshot&&r.reason?.length>=20);const prefix=b.attempts.slice(0,r.startIndex);assert.equal(require('../coach-review-core.cjs').hash(prefix),r.originalAttemptsHash,'Interrupted history changed');assert.ok(prefix.at(-1)?.status==='failed'&&prefix.at(-1).error.includes('timedOut=true'));assert.ok(prefix.filter(a=>a.status==='rejected').length<=b.correctionPolicy.maxCorrections,'No editorial round remains');return q.limits.maxAttempts+1;}assert.equal(r.maxAttempts,1,'One explicitly authorized technical recovery failure only');assert.equal(r.startIndex,q.limits.maxAttempts);assert.match(r.authorizationHash,/^[a-f0-9]{64}$/);assert.ok(r.snapshot&&r.reason?.length>=20);const prefix=b.attempts.slice(0,r.startIndex);assert.ok(prefix.every(a=>a.status==='failed'));assert.equal(require('../coach-review-core.cjs').hash(prefix),r.originalAttemptsHash,'Prior technical history changed');return q.limits.maxAttempts+r.maxAttempts;}
function validate(q,b){if(!enabled(b))return;assert.equal(b.correctionPolicy.maxCorrections,2);assert.ok(b.correctionPolicy.authorizationHash);assert.ok(!b.recovery&&!b.editorialAllowance,'Historical recovery must remain separate');assert.ok(b.attempts.length<=technicalLimit(q,b)+3);}
function latestRejection(b){return b.attempts.findLast(a=>a.status==='rejected');}
function mayStart(q,b){validate(q,b);const last=latestRejection(b);if(last?.critique?.review?.records.every(r=>r.accept))return false;return b.attempts.filter(a=>a.status==='failed'&&!require('./transport-recovery.cjs').resolvedFailures(b).has(a.id)).length<technicalLimit(q,b)&&b.attempts.filter(a=>a.status==='rejected').length<=b.correctionPolicy.maxCorrections;}
function exception(b){const last=latestRejection(b),rows=last?.critique?.review?.records||[];const bindingIssues=[...(last?.critique?.writerBindingReservations||[]).map(x=>({...x,source:'writer'})),...(last?.critique?.review?.bindings||[]).filter(x=>!x.compatible).map(x=>({...x,source:'reviewer'}))];b.status='exception';b.exception={bindingIssues,reason:rows.some(r=>!r.accept)?'editorial-corrections-exhausted':bindingIssues.length?'binding-provenance-blocked':'technical-retries-exhausted',reviewReference:last?.reviewReference||null,attemptIds:b.attempts.map(a=>a.id),acceptedStaged:rows.filter(r=>r.accept).map(r=>r.exampleId),unresolved:rows.filter(r=>!r.accept).map(r=>r.exampleId),integrated:false};for(const s of b.scenes)if(s.status!=='reference'&&!s.acceptedHash)s.status=b.exception.acceptedStaged.includes(s.exampleId)?'accepted-staged':b.exception.unresolved.includes(s.exampleId)?'unresolved':'blocked';return b.exception;}
function boundary(q,to){if(q.stopAfterBatch!==to){q.boundaryHistory||=[];q.boundaryHistory.push({at:new Date().toISOString(),from:q.stopAfterBatch||null,to,reason:'Explicit through-batch operator instruction; budgets and prior boundary retained.'});q.stopAfterBatch=to;}}
module.exports={technicalLimit,enabled,validate,latestRejection,mayStart,exception,boundary};
