'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const c=require('./core.cjs'),{command}=require('./worker.cjs');
function prepare(root,stage,q,b,input,writer,review,selection){
 assert.ok(!require('./coach2.cjs').active(input),'coach-2.0 versioned integration adapter required; never relabel evidence as coach-1.0');
 c.validateWriter(input,writer);c.validateReview(c.reviewerInput(input,writer),review);if(selection)require('./per-example.cjs').assertSelection(input,writer,review,selection.ids);else assert.ok(c.allAccepted(writer,review),'Rejected review or unresolved binding');c.copySource(root,stage);
 const singles=c.read(path.join(stage,'examples/authoring/single-scenes.json')),transfers=c.read(path.join(stage,'examples/authoring/stance-transfers.json'));
 const folder='editorial/local-'+q.id+'-'+b.id,reviewLedger=folder+'/single-batch-review.json',version=q.publicVersion+'+audit.'+q.id+'.'+b.id,records=[],amendments=[];
 for(const w of writer.records.filter(w=>!selection||selection.ids.includes(w.exampleId))){const original=input.records.find(o=>o.exampleId===w.exampleId),r=review.records.find(r=>r.exampleId===w.exampleId),before=original.before,after=structuredClone(before);assert.equal(c.hash(before.beats),w.beforeHash);if(w.decision==='revised'){after.beats=w.beats;after.exampleVersion=version;amendments.push({exampleId:w.exampleId,baselineLedger:'editorial/v0.25.0/single-dialogue-ledger.json',fromVersion:before.exampleVersion,toVersion:version,fromBeatsSha256:w.beforeHash,toBeatsSha256:c.hash(w.beats),reviewLedger});}
  const source=singles.records[original.key].examples,index=source.findIndex(s=>s.id===w.exampleId);assert.equal(c.hash(source[index]),c.hash(before),'Source changed since writer');source[index]=after;
  records.push({key:original.key,exampleId:w.exampleId,kind:'single',status:'internal-second-pass',rubricVersion:c.rubric.version,cards:[original.card],before,beforeBeatsSha256:w.beforeHash,after,afterBeatsSha256:c.hash(after.beats),firstPass:w.firstPass,secondPass:r.secondPass,hardGates:r.hardGates,hardGateEvidence:r.hardGateEvidence,decision:w.decision,mechanismDistinction:{mechanism:w.mechanism,confusableConcept:w.confusableConcept,distinguishingEvidenceRequired:w.distinguishingEvidence},recommendedEdit:w.reason,remainingConcern:r.reservation,writerReservation:w.reservation,alternativeComparison:r.alternativeComparison,independentHumanBlindRead:false,liveTested:false,freshModelReviewer:true,workerEvidence:'worker-evidence.json'});
 }
 const bindingRecords=[],bespokeDependencies=[];
 for(const raw of input.bindings){const changed=records.filter(r=>r.key===raw.key&&r.decision==='revised');if(!changed.length)continue;const assessment=writer.bindings.find(b=>b.key===raw.key),second=review.bindings.find(b=>b.key===raw.key);if(raw.transfer){const t=transfers.records[raw.key];const prior=selection?require('./per-example.cjs').transferBase(stage,raw,writer):{before:raw.transfer};if(!selection)assert.deepEqual(t,raw.transfer);t.seedBindingHashes=singles.records[raw.key].examples.map(s=>c.hash(s.beats));bindingRecords.push({cardId:raw.key,...prior,newSeedBindingHashes:t.seedBindingHashes,assessment:assessment.assessment,secondPassAssessment:second.assessment,scope:'All transfer fields inspected; only seed hashes rebound. Pair dialogue remains pending unless previously reviewed.'});}
  for(const pair of raw.bespokePairs)for(const r of changed.filter(r=>pair.seedRefs.includes(r.exampleId)))bespokeDependencies.push({exampleId:pair.id,seedRef:r.exampleId,historicalSeedDialogue:r.before.beats,baselineSeedHash:r.beforeBeatsSha256,currentSeedHash:r.afterBeatsSha256,pairDialogueHash:c.hash(pair.beats),assessment:assessment.assessment,secondPassAssessment:second.assessment,individuallyReviewed:false});
 }
 c.save(path.join(stage,'examples/authoring/single-scenes.json'),singles);c.save(path.join(stage,'examples/authoring/stance-transfers.json'),transfers);
 c.save(path.join(stage,reviewLedger),{schema:1,release:q.publicVersion,internalExampleVersion:version,rubricVersion:c.rubric.version,scope:'Bounded local model two-pass single-card review; not independent human approval.',records});
 c.save(path.join(stage,folder,'single-amendments.json'),{schema:1,release:q.publicVersion,amendments});
 c.save(path.join(stage,folder,'transfer-binding-review.json'),{schema:1,records:bindingRecords,bespokeDependencies,pendingPairFlags:[{exampleId:'S06+D49-b',status:'pending',separatelyScopedPairReviewRequired:true,reason:'Documented seed-description mismatch; not addressed by local single-card runner.'}]});
 c.save(path.join(stage,folder,'completion.json'),{schema:1,status:'complete',rubricVersion:c.rubric.version,sceneCount:records.length,reviewLedger,amendmentLedger:folder+'/single-amendments.json',newlyRewrittenSceneIds:records.filter(r=>r.decision==='revised').map(r=>r.exampleId),unchangedReviewedSceneIds:records.filter(r=>r.decision==='retained').map(r=>r.exampleId),unchangedReferenceSceneIds:b.scenes.filter(s=>s.status==='reference').map(s=>s.exampleId),pendingSceneIds:[],validation:'validation.json'});
 const progress=c.discover(stage).progress;
 if(selection){const p=path.join(stage,folder,'completion.json'),v=c.read(p);v.scope='Complete atomic group; not completion of the parent scheduling batch';v.parentBatch=selection.parentBatch;v.parentScopeSceneIds=b.scenes.map(s=>s.exampleId);v.parentPendingSceneIds=b.scenes.filter(s=>!s.acceptedHash&&s.status!=='reference'&&!selection.ids.includes(s.exampleId)).map(s=>s.exampleId);c.save(p,v);}
 c.save(path.join(stage,'editorial/local-audit-status.json'),{queue:q.id,batch:b.id,publicVersion:q.publicVersion,progress,completion:folder+'/completion.json',releaseValidation:'pending; internal batches do not create a public release',pendingPairFlags:['S06+D49-b']});
 const note='\n\n## Local audit checkpoint '+q.id+' / '+b.id+'\n\nInternal model review: '+progress.singlesReviewed+'/'+progress.singlesTotal+' singles; '+progress.pairsReviewed+'/'+progress.pairsTotal+' pairs. Evidence: `'+folder+'/completion.json`. Public release version remains '+q.publicVersion+'. Full release/browser/fresh-extraction validation remains a separate checkpoint boundary. S06+D49-b remains pending.\n';
 for(const f of ['CHECKPOINT-STATUS.md','docs/CODEX-HINT-AUDIT-HANDOFF.md'])fs.appendFileSync(path.join(stage,f),note);
 return {folder,records,amendments,progress};
}
function npmCli(){const candidates=[process.env.npm_execpath,path.join(path.dirname(process.execPath),'node_modules/npm/bin/npm-cli.js'),path.resolve(path.dirname(process.execPath),'../lib/node_modules/npm/bin/npm-cli.js')];const p=candidates.find(p=>p&&p.endsWith('.js')&&fs.existsSync(p));assert.ok(p,'Cannot locate installed npm CLI; no installation attempted');return p;}
async function validate(stage,logs,deadline){const results=[];for(const script of ['build:examples','audit:all','test']){assert.ok(Date.now()<deadline,'Elapsed-time limit before '+script);const r=await command(process.execPath,[npmCli(),'run',script],stage,path.join(logs,script.replace(':','-')),deadline-Date.now());results.push({script,...r});if(r.code!==0||r.timedOut){const e=Error(script+' failed or timed out; see '+r.log);e.validation=results;throw e;}}return results;}
function allowed(file,folder){const f=file.replaceAll('\\','/');return ['examples/authoring/single-scenes.json','examples/authoring/stance-transfers.json','examples/manifest.json','examples/manifest.js','sw.js','editorial/local-audit-status.json','CHECKPOINT-STATUS.md','docs/CODEX-HINT-AUDIT-HANDOFF.md'].includes(f)||f.startsWith('examples/data/')||f.startsWith(folder+'/');}
function makeTransaction(root,stage,journalPath,folder,guard){assert.deepEqual(c.fingerprint(root),guard,'Concurrent editor/source change before integration');const after=c.fingerprint(stage),entries=[];for(const file of new Set([...Object.keys(guard),...Object.keys(after)])){if(guard[file]===after[file])continue;if(file.replaceAll('\\','/')==='examples/authoring/pair-scenes.json')require('./binding-recovery.cjs').assertSourceChange(root,stage,folder);else if(['index.html','app.js','examples/library-client.js','examples/library-worker.js'].includes(file.replaceAll('\\','/'))){const normalize=p=>fs.readFileSync(p,'utf8').replace(/\?v=[a-zA-Z0-9.+_-]+/g,'?v=BUILD');assert.equal(normalize(path.join(root,file)),normalize(path.join(stage,file)),'Only generated asset addresses may change: '+file);}else assert.ok(allowed(file,folder),'Unexpected staging mutation: '+file);entries.push({file,before:guard[file]||null,after:after[file]||null});}const blob=path.join(path.dirname(journalPath),'transaction-files');for(const e of entries){if(e.after){const p=path.join(blob,e.after);fs.mkdirSync(blob,{recursive:true});fs.copyFileSync(path.join(stage,e.file),p);}}
 const journal={schema:1,root:path.resolve(root),status:'prepared',guard,after,entries,blob,folder};c.save(journalPath,journal);return journal;
}
function applyTransaction(journalPath,interruptAfter=Infinity){const j=c.read(journalPath),current=c.fingerprint(j.root),changes=new Map(j.entries.map(e=>[e.file,e]));for(const file of new Set([...Object.keys(j.guard),...Object.keys(j.after),...Object.keys(current)])){const e=changes.get(file);assert.ok(e?[e.before,e.after].includes(current[file]||null):current[file]===j.guard[file],'Concurrent source conflict: '+file);}
 let n=0;for(const e of j.entries){const target=path.resolve(j.root,e.file);assert.ok(target.startsWith(j.root+path.sep));if(e.after){const bytes=fs.readFileSync(path.join(j.blob,e.after));assert.equal(c.sha(bytes),e.after,'Transaction blob drift');fs.mkdirSync(path.dirname(target),{recursive:true});const tmp=target+'.audit-tmp';fs.writeFileSync(tmp,bytes);fs.renameSync(tmp,target);}else if(fs.existsSync(target))fs.unlinkSync(target);if(++n===interruptAfter)throw Error('Fixture interruption during integration');}
 assert.deepEqual(c.fingerprint(j.root),j.after,'Integrated source differs from validated staging');j.status='applied';c.save(journalPath,j);return j;
}
function stagePath(){return path.join(os.tmpdir(),'imprompt-stage-'+require('node:crypto').randomUUID());}
module.exports={prepare,npmCli,validate,makeTransaction,applyTransaction,stagePath,allowed};
