'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const c=require('./core.cjs'),w=require('./worker.cjs');
function recover(queueFile,batchId,evidenceFile,exclusive){
 assert.ok(exclusive,'Recovery requires the exclusive-editor condition');const q=c.read(queueFile),release=require('../local-audit-runner.cjs').lock(q.root,q.id);
 try{
 assert.equal(q.status,'stopped');const b=q.batches.find(b=>b.id===batchId);assert.ok(b&&b.status==='failed'&&!b.recovery,'Recovery must identify one failed batch without an existing recovery');assert.equal(q.batches.find(x=>x.status!=='complete').id,batchId);
 const evidence=c.read(path.resolve(evidenceFile));assert.equal(evidence.batch,batchId);assert.ok(evidence.reason?.length>=20);assert.deepEqual(evidence.beforeGuard,q.guard);assert.deepEqual(evidence.afterGuard,c.fingerprint(q.root),'Repair evidence does not match current source');
 const changes=[...new Set([...Object.keys(q.guard),...Object.keys(evidence.afterGuard)])].filter(f=>q.guard[f]!==evidence.afterGuard[f]);assert.deepEqual([...changes].sort(),[...evidence.reconciledFiles].sort(),'Every source change must be explicitly reconciled');
 assert.ok(evidence.endToEnd?.status==='passed','Real two-scene end-to-end evidence required');const testDir=path.resolve(evidence.endToEnd.directory),testInput=c.read(path.join(testDir,'writer.input.json')),testWriter=w.reuseWriter(testInput,testDir);assert.ok(testInput.records.length<=2&&new Set(testInput.records.map(r=>r.key)).size===1);c.validateWriter(testInput,testWriter.output);const testReview=c.read(path.join(testDir,'reviewer.json')),testProof=c.read(path.join(testDir,'reviewer.proof.json'));w.verifyTotals(testDir,'reviewer',testReview,testProof);assert.equal(c.hash(testReview),testProof.outputHash);assert.equal(testProof.freshInvocation,true);assert.equal(testProof.toolsUsed,false);c.validateReview(c.reviewerInput(testInput,testWriter.output),testReview);assert.ok(c.allAccepted(testWriter.output,testReview));
 const dir=path.dirname(queueFile),batchDir=path.join(dir,b.id),source=path.resolve(evidence.reuseWriterDirectory);assert.ok(b.attempts.some(a=>path.join(batchDir,a.id)===source),'Recovery writer must be from a preserved attempt in this batch');const input=c.writerInput(q.root,b),saved=w.reuseWriter(input,source);assert.ok(saved,'No proven writer artifact to recover');const derived=w.deriveTotals(saved.output,'writer');c.validateWriter(input,derived.output);
 const snapshot=dir+'.recovery-snapshot-'+Date.now();fs.cpSync(dir,snapshot,{recursive:true,errorOnExist:true,force:false});const index=b.attempts.length,id='attempt-'+String(index+1).padStart(2,'0'),dest=path.join(batchDir,id);fs.mkdirSync(dest);for(const file of fs.readdirSync(source).filter(f=>f.startsWith('writer.')&&!f.endsWith('.workspace.json')))fs.copyFileSync(path.join(source,file),path.join(dest,file),fs.constants.COPYFILE_EXCL);const recovered=w.finalizeTotals(dest,'writer');c.validateWriter(input,recovered.output);
 b.recovery={authorizedAt:new Date().toISOString(),reason:evidence.reason,evidence:path.resolve(evidenceFile),evidenceHash:c.hash(evidence),snapshot,startIndex:index,maxAttempts:q.limits.maxAttempts,recoveredFrom:source,derivedTotals:recovered.proof.derivedTotals||[]};b.attempts.push({id,status:'active',stage:'writer-validation',writerReusedFrom:path.basename(source),writerReference:path.join(dest,'writer.json'),startedAt:new Date().toISOString(),usage:[]});b.status='pending';for(const scene of b.scenes)if(scene.status!=='reference')scene.status='pending';q.guard=evidence.afterGuard;q.stopAfterBatch=b.id;q.stopReason='authorized-recovery-ready';c.save(queueFile,q);return b.recovery;
 }finally{release();}
}
module.exports={recover};
