'use strict';
// Carry only accepted, hash-matched model reviews; preserve each raw invocation.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const c=require('./core.cjs'),w=require('./worker.cjs');
function plan(input,writer,previousWriter,previousReview){
 c.validateWriter(input,previousWriter);c.validateReview(c.reviewerInput(input,previousWriter),previousReview);
 const pending=previousReview.records.filter(r=>!r.accept).map(r=>r.exampleId),keys=[...new Set(pending.map(id=>input.records.find(r=>r.exampleId===id).key))];assert.ok(pending.length>0,'No pending review to invoke');
 const carried=previousReview.records.filter(r=>r.accept).map(r=>r.exampleId);for(const id of carried)assert.equal(c.hash(writer.records.find(r=>r.exampleId===id)?.beats),previousReview.records.find(r=>r.exampleId===id).candidateHash,'Accepted candidate changed: '+id);
 const full=c.reviewerInput(input,writer);return {pending,keys,carried,input:{...full,records:full.records.filter(r=>keys.includes(r.card.id)).map(r=>({...r,reference:!pending.includes(r.exampleId)})),bindings:full.bindings.filter(b=>keys.includes(b.key))}};
}
function combine(input,writer,previousWriter,previousReview,partial){const selection=plan(input,writer,previousWriter,previousReview);c.validateReview(selection.input,partial);const output={records:previousReview.records.map(r=>selection.pending.includes(r.exampleId)?partial.records.find(n=>n.exampleId===r.exampleId):r),bindings:previousReview.bindings.map(b=>selection.keys.includes(b.key)?partial.bindings.find(n=>n.key===b.key):b)};c.validateReview(c.reviewerInput(input,writer),output);return {output,selection};}
function invocation(dir,role){const output=c.read(path.join(dir,role+'.json')),proof=c.read(path.join(dir,role+'.proof.json')),run=c.read(path.join(dir,role+'.process.json'));assert.equal(c.hash(output),proof.outputHash);assert.equal(proof.freshInvocation,true);assert.equal(proof.toolsUsed,false);w.verifyTotals(dir,role,output,proof);assert.equal(run.code,0);assert.equal(run.timedOut,false);assert.ok(run.command.includes('read-only')&&run.command.includes('--ephemeral'));assert.ok(!run.command.some(a=>/dangerously|ignore-rules|add-dir/.test(a)));const events=fs.readFileSync(path.join(dir,role+'.stdout.log'),'utf8').trim().split(/\r?\n/).map(JSON.parse);w.validateEvents(events,proof.rawOutputHash?c.read(path.join(dir,role+'.raw.json')):output);if(proof.rawOutputHash){const message=events.findLast(e=>e.type==='item.completed'&&e.item?.type==='agent_message');assert.equal(c.hash(JSON.parse(message.item.text)),proof.rawOutputHash);}return {output,proof};}
function readReview(dir,input,writer){return fs.existsSync(path.join(dir,'reviewer-reuse.json'))?verify(dir,input,writer).output:invocation(dir,'reviewer').output;}
function saveCombined(dir,previousDir,input,writer,partial,proof){assert.match(path.basename(previousDir),/^attempt-\d{2}$/);const previousWriter=c.read(path.join(previousDir,'writer.json')),previousReview=readReview(previousDir,input,previousWriter);const result=combine(input,writer,previousWriter,previousReview,partial),record={previousAttempt:path.basename(previousDir),previousWriterHash:c.hash(previousWriter),previousReviewHash:c.hash(previousReview),partialReviewHash:c.hash(partial),combinedReviewHash:c.hash(result.output),carriedIds:result.selection.carried,reviewedIds:result.selection.pending};c.save(path.join(dir,'reviewer-combined.json'),result.output);c.save(path.join(dir,'reviewer-reuse.json'),record);return {output:result.output,proof:{...proof,combinedOutputHash:record.combinedReviewHash,reuse:record}};}
function verify(dir,input,writer){const reuse=c.read(path.join(dir,'reviewer-reuse.json'));assert.match(reuse.previousAttempt,/^attempt-\d{2}$/);assert.ok(reuse.previousAttempt<path.basename(dir),'Review reuse must point to an earlier attempt');const previousDir=path.join(path.dirname(dir),reuse.previousAttempt);const pw=invocation(previousDir,'writer').output,pi=c.read(path.join(previousDir,'writer.input.json')),pr=readReview(previousDir,pi,pw);assert.deepEqual(pi,input,'Prior review used different originals or bindings');c.validateWriter(input,pw);const priorBlind=c.reviewerInput(input,pw);if(!fs.existsSync(path.join(previousDir,'reviewer-reuse.json')))assert.deepEqual(c.read(path.join(previousDir,'reviewer.input.json')),{...priorBlind,records:priorBlind.records.map(r=>({...r,candidateHash:c.hash(r.beats)}))});assert.equal(c.hash(pw),reuse.previousWriterHash);assert.equal(c.hash(pr),reuse.previousReviewHash);const partial=invocation(dir,'reviewer').output;assert.equal(c.hash(partial),reuse.partialReviewHash);const combined=combine(input,writer,pw,pr,partial);assert.deepEqual(reuse.carriedIds,combined.selection.carried);assert.deepEqual(reuse.reviewedIds,combined.selection.pending);assert.deepEqual(c.read(path.join(dir,'reviewer-combined.json')),combined.output);assert.equal(c.hash(combined.output),reuse.combinedReviewHash);const blind=combined.selection.input;assert.deepEqual(c.read(path.join(dir,'reviewer.input.json')),{...blind,records:blind.records.map(r=>({...r,candidateHash:c.hash(r.beats)}))});return {output:combined.output,blind};}
module.exports={plan,combine,invocation,saveCombined,verify,readReview};
